In [211]:
#importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy
import datetime as dt
import copy

In [2]:
train=pd.read_csv('c:/Users/LENOVO/My Documents/data sets/box-office_prediction/train.csv')
sample=pd.read_csv('c:/Users/LENOVO/My Documents/data sets/box-office_prediction/sample_submission.csv')
test=pd.read_csv('c:/Users/LENOVO/My Documents/data sets/box-office_prediction/test.csv')

In [4]:
train

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,2/20/15,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,8/6/04,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,10/10/14,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,3/9/12,122.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,2/5/09,118.0,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970
5,6,NaN,8000000,"[{'id': 16, 'name': 'Animation'}, {'id': 12, '...",NaN,tt0093743,en,Pinocchio and the Emperor of the Night,"Pinocchio and his friends, a glow worm and a m...",0.743274,...,8/6/87,83.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Pinocchio and the Emperor of the Night,NaN,"[{'cast_id': 6, 'character': 'Pinocchio (voice...","[{'credit_id': '52fe46f49251416c9106558b', 'de...",3261638
6,7,NaN,14000000,"[{'id': 27, 'name': 'Horror'}, {'id': 53, 'nam...",http://www.thepossessionmovie.com/,tt0431021,en,The Possession,A young girl buys an antique box at a yard sal...,7.286477,...,8/30/12,92.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Fear The Demon That Doesn't Fear God,The Possession,NaN,"[{'cast_id': 23, 'character': 'Clyde', 'credit...","[{'credit_id': '52fe4981c3a368484e12ee29', 'de...",85446075
7,8,NaN,0,"[{'id': 99, 'name': 'Documentary'}]",NaN,tt0391024,en,Control Room,A chronicle which provides a rare window into ...,1.949044,...,1/15/04,84.0,"[{'iso_639_1': 'ar', 'name': 'العربية'}, {'iso...",Released,Different channels. Different truths.,Control Room,"[{'id': 917, 'name': 'journalism'}, {'id': 163...","[{'cast_id': 2, 'character': 'Himself', 'credi...","[{'credit_id': '52fe47a69251416c750a0daf', 'de...",2586511
8,9,"[{'id': 256377, 'name': 'The Muppet Collection...",0,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",NaN,tt0117110,en,Muppet Treasure Island,After telling the story of Flint's last journe...,6.902423,...,2/16/96,100.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Set sail for Muppet mayhem!,Muppet Treasure Island,"[{'id': 2041, 'name': 'island'}, {'id': 4418, ...","[{'cast_id': 1, 'character': 'Long John Silver...","[{'credit_id': '52fe43c89251416c7501deb3', 'de...",34327391
9,10,NaN,6000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10402, '...",NaN,tt0310281,en,A Mighty Wind,"In ""A Mighty Wind"", director Christopher Guest...",4.672036,...,4/16/03,91.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"Back together for the first time, again.",A Mighty Wind,"[{'id': 11800, 'name': 'mockumentary'}, {'id':...","[{'cast_id': 24, 'character': 'Jonathan Steinb...","[{'credit_id': '52fe45609251416c750545b3', 'de...",18750246
10,11,"[{'id': 1575, 'name': 'Rocky Collection', 'pos...",1000000,"[{'id': 18, 'name': 'Drama'}]",NaN,tt0075148,en,Rocky,"When world heavyweight boxing champion, Apollo...",14.774066,...,11/21/76,119.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,His whole life was a million-to-one shot.,Rocky,"[{'id': 240, 'name': 'underdog'}, {'id': 276, ...","[{'cast_id': 16, 'character': 'Rocky Balboa', ...","[{'credit_id': '579948e9c3a36874e9007b0b', 'de...",117235147
11,12,"[{'id': 48190, 'name': 'Revenge of the Nerds C...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt0093857,en,Revenge of the Nerds II: Nerds in Paradise,The members of the Lambda Lambda Lambda frater...,10.543750,...,7/10/87,98.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,They're Back!,Revenge of the Nerds II: Nerds in Paradise,"[{'id': 5801, 'name': 'nerd'}, {'id': 6876, 'n...","[{'cast_id': 2, 'character': 'Lewis Skolnick',...","[{'credit_id': '52fe46f49251416c750891e9', 'de...",22642033
12,13,NaN,15000000,"[{'id': 18, 'name': 'Drama'}]",http://www.dreamworks.com/ab/,tt0169547,en,American Beauty,"Lester Burnham, a depressed suburban father in...",20.726578,...,9/15/99,122.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Look closer.,American Beauty,"[{'id': 255, 'name': 'male nudity'}, {'id': 29...","[{'cast_id': 6, 'character': 'Lester Burnham',...","[{'credit_id': '52fe420ec3a36847f80007c5', 'de...",356296601
13,14,"[{'id': 91698, 'name': 'Chili Palmer Collectio...",53000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 80, 'nam...",NaN,tt0377471,en,Be Cool,"Disenchanted with the movie industry, Chili Pa...",13.314233,...,3/4/05,118.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Everyone is looking for the next big hit,Be Cool,"[{'id': 3605, 'name': 'baseball bat'}, {'id': ...","[{'cast_id': 4, 'character': 'Chili Palmer', '...","[{'credit_id': '52fe43cbc3a36847f807039f', 'de...",95226116
14,15,NaN,102000000,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt0181689,en,Minority Report,John Anderton is a top 'Precrime' cop in the l...,20.666063,...,6/20/02,145.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,The system is perfect until it comes after you.,Minority Report,"[{'id': 476, 'name': 'self-fulfilling prophecy...","[{'cast_id': 5, 'character': 'Chief John Ander...","[{'credit_id': '52fe4223c3a36847f8006f3d', 'de...",358372926
15,16,NaN,500000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",http://skinningmovie.com/synopsis.htm,tt1129437,sr,Šišanje,Novica is a mathematics champion in a Belgrade...,1.018477,...,10/6/10,97.0,"[{'iso_639_1': 'sr', 'name': 'Srpski'}]",Released,Life is sometimes rude game: one mistake can b...,Skinning,"[{'id': 379, 'name': 'skinhead'}, {'id': 7492,...","[{'cast_id': 1001, 'character': 'Novica', 'cre...","[{'credit_id': '52fe4927c3a36847f818bb5f', 'de...",198
16,17,NaN,26000000,"[{'id': 27, 'name': 'Horror'}, {'id': 53, 'nam...",NaN,tt0421239,en,Red Eye,After attending the funeral of her grandmother...,6.336927,...,8/4/05,85.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Fear takes flight.,Red Eye,"[{'id': 1562, 'name': 'hostage'}, {'id': 2250,...","[{'cast_id': 1, 'character': 'Lisa Reisert', '...","[{'credit_id': '52fe44449251416c7502eb99', 'de...",57891803
17,18,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",NaN,tt1700845,en,The Invisible Woman,"In 1857, at the height of his fame and fortune...",4.183558,...,12/25/13,111.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,His greatest story was the one he could never ...,The Invisible Woman,"[{'id': 5565, 'name': 'biography'}, {'id': 180...","[{'cast_id': 7, 'character': 'Charles Dickens'...","[{'credit_id': '53b94a260e0a2676c7009b37', 'de...",1234254
18,19,NaN,8000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",NaN,tt1487118,en,Chalet Girl,While working a job at an exclusive ski resort...,6.496259,...,2/2/11,96.0,"[{'iso_639_1': 'de', 'name': 'Deutsch'}, {'iso...",Released,How to marry a billionaire.,Chalet Girl,"[{'id': 271, 'name': 'competition'}, {'id': 35...","[{'cast_id': 2, 'character': 'Kim Matthews', '...","[{'credit_id': '52fe495ac3a36847f8195d4d', 'de...",1749457
19,20,"[{'id': 9518, 'name': 'The Transporter Collect...",32000000,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt0388482,en,Transporter 2,Professional driver Frank Martin is living in ...,11.359659,...,8/2/05,87.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,The Best In The Business Is Back In The Game.,Transporter 2,"[{'id': 779, 'name': 'martial arts'}, {'id': 1...","[{'cast_id': 1, 'character': 'Frank Martin', '...","[{'credit_id': '52fe44e9c3a36847f80b154d', 'de...",85167639
20,21,NaN,80000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 10751...",NaN,tt0120738,en,Lost in Space,The prospects for continuing life on Earth in ...,12.000579,...,4/3/98,130.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"Danger, Will Robinson!",Lost in Space,"[{'id': 4379, 'name': 'time travel'}, {'id': 1...","[{'cast_id': 26, 'character': 'Dr. Zachary Smi...","[{'credit_id': '52fe433bc3a36847f80448b9', 'de...",136159423
21,22,"[{'id': 9735, 'name': 'Friday the 13th Collect...",4000000,"[{'id': 27, 'name': 'Horror'}, {'id': 53, 'nam...",NaN,tt0083972,en,Friday the 13th Part III,An idyllic summer turns into a nightmare of un...,7.992290,...,8/13/82,95.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,There's nowhere to hide. We dare you to try.,Friday the 13th Part III,"[{'id': 1889, 'name': 'lake'}, {'id': 5767, 'n...","[{'cast_id': 1, 'character': 'Chris Higgins', ...","[{'credit_id': '52fe4523c3a36847f80be885', 'de...",36690067
22,23,"[{'id': 207621, 'name': 'V/H/S Collection', 'p...",0,"[{'id': 53, 'name': 'Thriller'}, {'id': 27, 'n...",http://www.magnetreleasing.com/vhs/,tt2105044,en,V/H/S,When a group of misfits is hired by an unknown...,7.820787,...,7/28/12,116.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,This collection is killer.,V/H/S,"[{'id': 6435, 'name': 'webcam'}, {'id': 9706, ...","[{'cast_id': 1, 'character': 'Gary', 'credit_i...","[{'credit_id': '52fe48ee9251416c9109d113', 'de...",100345
23,24,NaN,0,"[{'id': 53, 'name': 'Thriller'}, {'id': 9648, ...",http://insightthemovie.com/,tt1687277,en,InSight,"Kaitlyn, an ER nurse who is tending to a young...",1.323333,...,9/2/11,92.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Fear what you see,InSight,NaN,"[{'cast_id': 1037, 'character': 'Det. Canto', ...","[{'credit_id': '52fe4980c3a368484e12e993', 'de...",17011
24,25,NaN,0,"[{'id': 27, 'name': 'Horror'}, {'id': 35, 'nam...",http://www.blacksheep-themovie.com/,tt0779982,en,Black Sheep,A genetic engineering experiment gone horribly...,7.434577,...,9/9/06,87.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,There are over 40 million sheep in New Zealand...,Black Sheep,"[{'id': 2658, 'name': 'new zealand'}, {'id': 3...","[{'cast_id': 9, 'character': 'Henry Oldfield',...","[{'credit_id': '52fe43a0c3a36847f8063031', 'de...",4947717
25,26,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 27, 'nam...",NaN,tt0104139,en,Dr. Giggles,"In 1957, Evan Rendell flees after his father i...",1.252367,...,10/23/92,95.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Doctor is out... of his mind.,Dr. Giggles,NaN,"[{'cast_id': 2, 'character': 'Dr. Evan Rendell...","[{'credit_id': '54b1fb3b925141144f000991', 'de...",8403433
26,27,NaN,10000000,"[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...",NaN,tt0120176,en,The Spanish Prisoner,An employee of a corporation with a lucrative ...,4.305735,...,9/8/97,110.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It's the oldest con in the book.,The Spanish Prisoner,"[{'id': 811, 'name': 'dialogue'}, {'id': 2246,...","[{'cast_id': 1, 'character': 'Jimmy Dell', 'cr...","[{'credit_id': '52fe45cfc3a368484e07017d', 'de...",13835130
27,28,NaN,11000000,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",NaN,tt1486834,en,What If,"Wallace, a medical school dropout, has been re...",10.841891,...,9/7/13,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,...being friends has its benefits?,What If,"[{'id': 10556, 'name': 'male female relationsh...","[{'cast_id': 5, 'character': 'Wallace', 'credi...","[{'credit_id': '52fe4db4c3a368484e1f8003', 'de...",7847000
28,29,NaN,6000000,"[{'id': 16, 'name': 'Animation'}]",NaN,tt0092106,en,The Transformers: The Movie,The Autobots must stop a colossal planet-consu...,6.759181,...,8/8/86,84.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Beyond good. Beyond evil. Beyond your wildest ...,The Transformers: The Movie,"[{'id': 4290, 'name': 'toy'}, {'id': 4375, 'na...","[{'cast_id': 10, 'character': 'Hot Rod/Rodimus...","[{'credit_id': '52fe431bc3a36847f803ab1b', 'de...",5849647
29,30,NaN,45000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",NaN,tt0264472,en,Changing Lanes,A rush-hour fender-bender on New York City's c...,7.818620,...,4/7/02,89.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"An ambitious lawyer, a desperate father, they ...",Changing Lanes,"[{'id': 242, 'name': 'new york'}, {'id': 4056,...","[{'cast_id': 1, 'character': 'Gavin Banek', 'c...","[{'credit_id': '52fe42fbc3a36847f80317d5', 'de...",94935764
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2970,2971,NaN,25000000,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",NaN,tt0103855,en,The Bodyguard,A former Secret Service agent grudgingly takes...,9.805017,...,11/25/92,129.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Never let her out of your sight. Never let you...,The Bodyguard,"[{'id': 1156, 'name': 'sister sister relations...","[{'cast_id': 17, 'character': 'Rachel Marron',...","[{'credit_id': '52fe425ec3a36847f8019133', 'de...",411006740
2971,2972,NaN,20000000,"[{'id': 14, 'name': 'Fantasy'}, {'id': 35, 'na...",NaN,tt0100201,en,Mr. Destiny,Larry Burrows is unhappy and feels powerless o...,4.414928,...,10/12/90,110.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Larry Burrows Wished For It All... Until All T...,Mr. Destiny,"[{'id': 4896, 'name': 'wish'}]","[{'cast_id': 1, 'character': 'Larry Burrows', ...","[{'credit_id': '52fe4360c3a36847f804f873', 'de...",15379253
2972,2973,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt0482930,cn,龍虎門,Dragon Tiger Gate is a 2006 Hong Kong martial ...,4.154861,...,7/27/06,94.0,"[{'iso_639_1': 'cn', 'name': '广州话 / 廣州話'}]",Released,NaN,Dragon Tiger Gate,"[{'id': 780, 'name': 'kung fu'}]","[{'cast_id': 1, 'character': 'Dragon Wong', 'c...","[{'credit_id': '52fe46869251416c7507b08f', 'de...",8685526
2973,2974,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10751, '...",NaN,tt0089652,en,My Science Project,Michael and Ellie break into a military junkya...,3.868014,...,8/9/85,94.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,We must not destroy the world.,My Science Project,"[{'id': 4379, 'name': 'time travel'}, {'id': 1...","[{'cast_id': 1, 'character': ""Michael 'Mike' H...","[{'credit_id': '52fe476e9251416c75099025', 'de...",4122748
2974,2975,"[{'id': 149704, 'name': 'Alone in the Dark Col...",20000000,"[{'id': 28, 'name': 'Action'}, {'id': 14, 'nam...",NaN,tt0369226,en,Alone in the Dark,Edward Carnby is a private investigator specia...,5.871243,...,1/28/05,96.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Can mankind defeat the army of darkness unleas...,Alone in the Dark,"[{'id': 703, 'name': 'detective'}, {'id': 1299...","[{'cast_id': 12, 'character': 'Edward Carnby',...","[{'credit_id': '52fe44bd9251416c7503f4f1', 'de...",10442808
2975,2976,NaN,45000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 35, '...",http://www.aliensintheatticmovie.com/,tt0775552,en,Aliens in the Attic,"It's summer vacation, but the Pearson family k...",11.618472,...,7/31/09,86.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The aliens vs. the Pearsons,Aliens in the Attic,"[{'id': 9951, 'name': 'alien'}, {'id': 10267, ...","[{'cast_id': 4, 'character': 'Tom Pearson', 'c...","[{'credit_id': '537830e40e0a261425003dca', 'de...",57881056
2976,2977,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 80, 'nam...",NaN,tt0186045,en,Drowning Mona,The recently deceased Mona Dearly (Bette Midle...,4.372616,...,3/3/00,96.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The death of Mona Dearly wasn't so much a whod...,Drowning Mona,"[{'id': 3301, 'name': 'suspicion'}, {'id': 387...","[{'cast_id': 1, 'character': 'Chief Wyatt Rash...","[{'credit_id': '52fe44bbc3a368484e033ccf', 'de...",15427192
2977,2978,NaN,53000000,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",http://angeleyesmovie.warnerbros.com/index_nof...,tt0225071,en,Angel Eyes,A story about a seemingly unlikely couple who ...,5.396200,...,5/15/01,102.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"The deeper you look, the more you will find.",Angel Eyes,"[{'id': 9844, 'name': 'car crash'}, {'id': 150...","[{'cast_id': 1, 'character': 'Sharon Pogue', '...","[{'credit_id': '52fe4427c3a36847f8085447', 'de...",29700000
2978,2979,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...",NaN,tt0120879,en,Velvet Goldmine,Almost a decade has elapsed since Bowiesque gl...,16.529300,...,10/23/98,119.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Style matters. Even when it comes to murder.,Velvet Goldmine,"[{'id': 237, 'name': 'gay'}, {'id': 1025, 'nam...","[{'cast_id': 2, 'character': 'Curt Wild', 'cre...","[{'credit_id': '52fe4316c3a36847f803946d', 'de...",1053788
2979,2980,NaN,35000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",http://www.theback-upplan.com/,tt1212436,en,The Back-Up Plan,"When Zoe tires of looking for Mr. Right, she d...",6.629999,...,4/23/10,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"Fall in love, get married, have a baby. Not ne...",The Back-Up Plan,"[{'id': 5091, 'name': 'kiss'}, {'id': 5098, 'n...","[{'cast_id': 22, 'character': 'Zoe', 'credit_i...","[{'credit_id': '52fe457e9251416c91034559', 'de...",77477008
2980,2981,NaN,300000,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",https://www.facebook.com/Actionherobiju/,tt5320514,ml,ആക്ഷൻ ഹീറോ ബിജു,Biju is an honest policeman who fights the inj...,0.350207,...,2/4/16,144.0,"[{'iso_639_1': 'ml', 'name': ''}]",Released,A ride with a police officer,Action Hero Biju,"[{'id': 1252, 'name': 'suicide attempt'}, {'id...","[{'cast_id': 1, 'character': 'Sub-Inspector Bi...","[{'credit_id': '56b4d47f92514112b90045f6', 'de...",2500000
2981,2982,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,tt4158876,en,Other People,"David, a struggling comedy writer fresh off fr...",3.069108,...,9/9/16,97.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Other People,"[{'id': 234102, 'name': 'misfits'}]","[{'cast_id': 0, 'character': 'David', 'credit_...","[{'credit_id': '57d923309251415959005090', 'de...",93000
2982,2983,NaN,500000,"[{'id': 18, 'name': 'Drama'}]",NaN,tt2063781,en,Smashed,Kate and Charlie like to have a good time. The...,4.893812,...,9/12/12,85.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Smashed,NaN,"[{'cast_id': 1001, 'character': 'Kate Hannah',...","[{'credit_id': '557455c1c3a3686b7d003df7', 'de...",376597

In [114]:
#train.homepage.value_counts() : remove
#train.belongs_to_collection.value_counts() : remove
#overview
#poster path

872

In [5]:
train.isnull().sum()

id                          0
belongs_to_collection    2396
budget                      0
genres                      7
homepage                 2054
imdb_id                     0
original_language           0
original_title              0
overview                    8
popularity                  0
poster_path                 1
production_companies      156
production_countries       55
release_date                0
runtime                     2
spoken_languages           20
status                      0
tagline                   597
title                       0
Keywords                  276
cast                       13
crew                       16
revenue                     0
dtype: int64

In [10]:
gen=train['genres'].str.split(',',n=100,expand=True)

In [7]:
gen

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,[{'id': 35,'name': 'Comedy'}],None,None,None,None,None,None,None,None,None,None,None,None
1,[{'id': 35,'name': 'Comedy'},{'id': 18,'name': 'Drama'},{'id': 10751,'name': 'Family'},{'id': 10749,'name': 'Romance'}],None,None,None,None,None,None
2,[{'id': 18,'name': 'Drama'}],None,None,None,None,None,None,None,None,None,None,None,None
3,[{'id': 53,'name': 'Thriller'},{'id': 18,'name': 'Drama'}],None,None,None,None,None,None,None,None,None,None
4,[{'id': 28,'name': 'Action'},{'id': 53,'name': 'Thriller'}],None,None,None,None,None,None,None,None,None,None
5,[{'id': 16,'name': 'Animation'},{'id': 12,'name': 'Adventure'},{'id': 10751,'name': 'Family'}],None,None,None,None,None,None,None,None
6,[{'id': 27,'name': 'Horror'},{'id': 53,'name': 'Thriller'}],None,None,None,None,None,None,None,None,None,None
7,[{'id': 99,'name': 'Documentary'}],None,None,None,None,None,None,None,None,None,None,None,None
8,[{'id': 28,'name': 'Action'},{'id': 35,'name': 'Comedy'},{'id': 10402,'name': 'Music'},{'id': 10751,'name': 'Family'},{'id': 12,'name': 'Adventure'}],None,None,None,None
9,[{'id': 35,'name': 'Comedy'},{'id': 10402,'name': 'Music'}],None,None,None,None,None,None,None,None,None,None
10,[{'id': 18,'name': 'Drama'}],None,None,None,None,None,None,None,None,None,None,None,None
11,[{'id': 35,'name': 'Comedy'}],None,None,None,None,None,None,None,None,None,None,None,None
12,[{'id': 18,'name': 'Drama'}],None,None,None,None,None,None,None,None,None,None,None,None
13,[{'id': 35,'name': 'Comedy'},{'id': 80,'name': 'Crime'}],None,None,None,None,None,None,None,None,None,None
14,[{'id': 28,'name': 'Action'},{'id': 53,'name': 'Thriller'},{'id': 878,'name': 'Science Fiction'},{'id': 9648,'name': 'Mystery'}],None,None,None,None,None,None
15,[{'id': 28,'name': 'Action'},{'id': 80,'name': 'Crime'},{'id': 18,'name': 'Drama'}],None,None,None,None,None,None,None,None
16,[{'id': 27,'name': 'Horror'},{'id': 53,'name': 'Thriller'}],None,None,None,None,None,None,None,None,None,None
17,[{'id': 18,'name': 'Drama'},{'id': 10749,'name': 'Romance'}],None,None,None,None,None,None,None,None,None,None
18,[{'id': 35,'name': 'Comedy'},{'id': 10749,'name': 'Romance'}],None,None,None,None,None,None,None,None,None,None
19,[{'id': 28,'name': 'Action'},{'id': 53,'name': 'Thriller'},{'id': 80,'name': 'Crime'}],None,None,None,None,None,None,None,None
20,[{'id': 12,'name': 'Adventure'},{'id': 10751,'name': 'Family'},{'id': 878,'name': 'Science Fiction'}],None,None,None,None,None,None,None,None
21,[{'id': 27,'name': 'Horror'},{'id': 53,'name': 'Thriller'}],None,None,None,None,None,None,None,None,None,None
22,[{'id': 53,'name': 'Thriller'},{'id': 27,'name': 'Horror'}],None,None,None,None,None,None,None,None,None,None
23,[{'id': 53,'name': 'Thriller'},{'id': 9648,'name': 'Mystery'},{'id': 10769,'name': 'Foreign'}],None,None,None,None,None,None,None,None
24,[{'id': 27,'name': 'Horror'},{'id': 35,'name': 'Comedy'}],None,None,None,None,None,None,None,None,None,None
25,[{'id': 35,'name': 'Comedy'},{'id': 27,'name': 'Horror'},{'id': 9648,'name': 'Mystery'},{'id': 53,'name': 'Thriller'}],None,None,None,None,None,None
26,[{'id': 80,'name': 'Crime'},{'id': 18,'name': 'Drama'},{'id': 9648,'name': 'Mystery'},{'id': 53,'name': 'Thriller'}],None,None,None,None,None,None
27,[{'id': 18,'name': 'Drama'},{'id': 35,'name': 'Comedy'},{'id': 10749,'name': 'Romance'}],None,None,None,None,None,None,None,None
28,[{'id': 16,'name': 'Animation'}],None,None,None,None,None,None,None,None,None,None,None,None
29,[{'id': 28,'name': 'Action'},{'id': 12,'name': 'Adventure'},{'id': 80,'name': 'Crime'},{'id': 53,'name': 'Thriller'}],None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2970,[{'id': 53,'name': 'Thriller'},{'id': 28,'name': 'Action'},{'id': 18,'name': 'Drama'},{'id': 10402,'name': 'Music'},{'id': 10749,'name': 'Romance'}],None,None,None,None
2971,[{'id': 14,'name': 'Fantasy'},{'id': 35,'name': 'Comedy'},{'id': 878,'name': 'Science Fiction'},{'id': 10749,'name': 'Romance'}],None,None,None,None,None,None
2972,[{'id': 28,'name': 'Action'},{'id': 53,'name': 'Thriller'}],None,None,None,None,None,None,None,None,None,None
2973,[{'id': 35,'name': 'Comedy'},{'id': 10751,'name': 'Family'},{'id': 14,'name': 'Fantasy'},{'id': 878,'name': 'Science Fiction'}],None,None,None,None,None,None
2974,[{'id': 28,'name': 'Action'},{'id': 14,'name': 'Fantasy'},{'id': 27,'name': 'Horror'},{'id': 53,'name': 'Thriller'}],None,None,None,None,None,None
2975,[{'id': 12,'name': 'Adventure'},{'id': 35,'name': 'Comedy'},{'id': 10751,'name': 'Family'},{'id': 14,'name': 'Fantasy'},{'id': 878,'name': 'Science Fiction'}],None,None,None,None
2976,[{'id': 35,'name': 'Comedy'},{'id': 80,'name': 'Crime'},{'id': 9648,'name': 'Mystery'}],None,None,None,None,None,None,None,None
2977,[{'id': 18,'name': 'Drama'},{'id': 10749,'name': 'Romance'},{'id': 53,'name': 'Thriller'}],None,None,None,None,None,None,None,None
2978,[{'id': 18,'name': 'Drama'},{'id': 10402,'name': 'Music'}],None,None,None,None,None,None,None,None,None,None
2979,[{'id': 35,'name': 'Comedy'},{'id': 10749,'name': 'Romance'}],None,None,None,None,None,None,None,None,None,None
2980,[{'id': 28,'name': 'Action'},{'id': 35,'name': 'Comedy'},{'id': 80,'name': 'Crime'}],None,None,None,None,None,None,None,None
2981,[{'id': 18,'name': 'Drama'}],None,None,None,None,None,None,None,None,None,None,None,None
2982,[{'id': 18,'name': 'Drama'}],None,None,None,None,None,None,None,None,None,None,None,None
2983,[{'id': 18,'name': 'Drama'},{'id': 10749,'name': 'Romance'}],None,None,None,None,None,None,None,None,None,None
2984,[{'id': 28,'name': 'Action'},{'id': 53,'name': 'Thriller'},{'id': 80,'name': 'Crime'}],None,None,None,None,None,None,None,None
2985,[{'id': 18,'name': 'Drama'},{'id': 53,'name': 'Thriller'},{'id': 80,'name': 'Crime'},{'id': 9648,'name': 'Mystery'}],None,None,None,None,None,None
2986,[{'id': 28,'name': 'Action'},{'id': 18,'name': 'Drama'},{'id': 53,'name': 'Thriller'}],None,None,None,None,None,None,None,None
2987,[{'id': 27,'name': 'Horror'},{'id': 878,'name': 'Science Fiction'}],None,None,None,None,None,None,None,None,None,None
2988,[{'id': 18,'name': 'Drama'}],None,None,None,None,None,None,None,None,None,None,None,None
2989,[{'id': 16,'name': 'Animation'},{'id': 10751,'name': 'Family'}],None,None,None,None,None,None,None,None,None,None
2990,[{'id': 28,'name': 'Action'},{'id': 35,'name': 'Comedy'}],None,None,None,None,None,None,None,None,None,None
2991,[{'id': 18,'name': 'Drama'},{'id': 10751,'name': 'Family'},{'id': 10749,'name': 'Romance'},{'id': 10402,'name': 'Music'}],None,None,None,None,None,None
2992,[{'id': 28,'name': 'Action'},{'id': 12,'name': 'Adventure'},{'id': 18,'name': 'Drama'},{'id': 10751,'name': 'Family'},{'id': 14,'name': 'Fantasy'}],None,None,None,None
2993,[{'id': 35,'name': 'Comedy'},{'id': 18,'name': 'Drama'}],None,None,None,None,None,None,None,None,None,None
2994,[{'id': 18,'name': 'Drama'}],None,None,None,None,None,None,None,None,None,None,None,None
2995,[{'id': 35,'name': 'Comedy'},{'id': 10749,'name': 'Romance'}],None,None,None,None,None,None,None,None,None,None
2996,[{'id': 18,'name': 'Drama'},{'id': 10402,'name': 'Music'}],None,None,None,None,None,None,None,None,None,None
2997,[{'id': 80,'name': 'Crime'},{'id': 28,'name': 'Action'},{'id': 9648,'name': 'Mystery'},{'id': 53,'name': 'Thriller'}],None,None,None,None,None,None
2998,[{'id': 35,'name': 'Comedy'},{'id': 10749,'name': 'Romance'}],None,None,None,None,None,None,None,None,None,None
2999,[{'id': 53,'name': 'Thriller'},{'id': 28,'name': 'Action'},{'id': 9648,'name': 'Mystery'}],None,None,None,None,None,None,None,None

In [11]:
gen=gen.iloc[:,[1,3,5,7,9,11,13]]

In [12]:
gen.fillna('unknown',inplace=True)

In [13]:
for i in range(0,gen.shape[1]):
    gen1=gen.iloc[:,i]
    import re
    for i in range(0,gen1.shape[0]):
        m=re.search(': (.+?)}',gen1[i])
        if m:
            found=m.group(1)
            gen1[i]=found[1:-1]

In [73]:
gen

,1,3,5,7,9,11,13
0,Comedy,unknown,unknown,unknown,unknown,unknown,unknown
1,Comedy,Drama,Family,Romance,unknown,unknown,unknown
2,Drama,unknown,unknown,unknown,unknown,unknown,unknown
3,Thriller,Drama,unknown,unknown,unknown,unknown,unknown
4,Action,Thriller,unknown,unknown,unknown,unknown,unknown
5,Animation,Adventure,Family,unknown,unknown,unknown,unknown
6,Horror,Thriller,unknown,unknown,unknown,unknown,unknown
7,Documentary,unknown,unknown,unknown,unknown,unknown,unknown
8,Action,Comedy,Music,Family,Adventure,unknown,unknown
9,Comedy,Music,unknown,unknown,unknown,unknown,unknown
10,Drama,unknown,unknown,unknown,unknown,unknown,unknown
11,Comedy,unknown,unknown,unknown,unknown,unknown,unknown
12,Drama,unknown,unknown,unknown,unknown,unknown,unknown
13,Comedy,Crime,unknown,unknown,unknown,unknown,unknown
14,Action,Thriller,Science Fiction,Mystery,unknown,unknown,unknown
15,Action,Crime,Drama,unknown,unknown,unknown,unknown
16,Horror,Thriller,unknown,unknown,unknown,unknown,unknown
17,Drama,Romance,unknown,unknown,unknown,unknown,unknown
18,Comedy,Romance,unknown,unknown,unknown,unknown,unknown
19,Action,Thriller,Crime,unknown,unknown,unknown,unknown
20,Adventure,Family,Science Fiction,unknown,unknown,unknown,unknown
21,Horror,Thriller,unknown,unknown,unknown,unknown,unknown
22,Thriller,Horror,unknown,unknown,unknown,unknown,unknown
23,Thriller,Mystery,Foreign,unknown,unknown,unknown,unknown
24,Horror,Comedy,unknown,unknown,unknown,unknown,unknown
25,Comedy,Horror,Mystery,Thriller,unknown,unknown,unknown
26,Crime,Drama,Mystery,Thriller,unknown,unknown,unknown
27,Drama,Comedy,Romance,unknown,unknown,unknown,unknown
28,Animation,unknown,unknown,unknown,unknown,unknown,unknown
29,Action,Adventure,Crime,Thriller,unknown,unknown,unknown
...,...,...,...,...,...,...,...
2970,Thriller,Action,Drama,Music,Romance,unknown,unknown
2971,Fantasy,Comedy,Science Fiction,Romance,unknown,unknown,unknown
2972,Action,Thriller,unknown,unknown,unknown,unknown,unknown
2973,Comedy,Family,Fantasy,Science Fiction,unknown,unknown,unknown
2974,Action,Fantasy,Horror,Thriller,unknown,unknown,unknown
2975,Adventure,Comedy,Family,Fantasy,Science Fiction,unknown,unknown
2976,Comedy,Crime,Mystery,unknown,unknown,unknown,unknown
2977,Drama,Romance,Thriller,unknown,unknown,unknown,unknown
2978,Drama,Music,unknown,unknown,unknown,unknown,unknown
2979,Comedy,Romance,unknown,unknown,unknown,unknown,unknown
2980,Action,Comedy,Crime,unknown,unknown,unknown,unknown
2981,Drama,unknown,unknown,unknown,unknown,unknown,unknown
2982,Drama,unknown,unknown,unknown,unknown,unknown,unknown
2983,Drama,Romance,unknown,unknown,unknown,unknown,unknown
2984,Action,Thriller,Crime,unknown,unknown,unknown,unknown
2985,Drama,Thriller,Crime,Mystery,unknown,unknown,unknown
2986,Action,Drama,Thriller,unknown,unknown,unknown,unknown
2987,Horror,Science Fiction,unknown,unknown,unknown,unknown,unknown
2988,Drama,unknown,unknown,unknown,unknown,unknown,unknown
2989,Animation,Family,unknown,unknown,unknown,unknown,unknown
2990,Action,Comedy,unknown,unknown,unknown,unknown,unknown
2991,Drama,Family,Romance,Music,unknown,unknown,unknown
2992,Action,Adventure,Drama,Family,Fantasy,unknown,unknown
2993,Comedy,Drama,unknown,unknown,unknown,unknown,unknown
2994,Drama,unknown,unknown,unknown,unknown,unknown,unknown
2995,Comedy,Romance,unknown,unknown,unknown,unknown,unknown
2996,Drama,Music,unknown,unknown,unknown,unknown,unknown
2997,Crime,Action,Mystery,Thriller,unknown,unknown,unknown
2998,Comedy,Romance,unknown,unknown,unknown,unknown,unknown
2999,Thriller,Action,Mystery,unknown,unknown,unknown,unknown

In [15]:
unique=copy.copy(set(gen.loc[:,1]))

In [16]:
unique=list(unique)

In [17]:
unique

['War',
 'Music',
 'Comedy',
 'Action',
 'Adventure',
 'TV Movie',
 'Drama',
 'History',
 'unknown',
 'Family',
 'Western',
 'Foreign',
 'Thriller',
 'Mystery',
 'Crime',
 'Animation',
 'Horror',
 'Science Fiction',
 'Documentary',
 'Romance',
 'Fantasy']

In [76]:
new_gen=pd.DataFrame(columns=unique,index=np.arange(0,3000,1))

In [80]:
for j in range(0,len(new_gen.columns)):
    for i in range(0,gen.shape[0]):
        new_gen.iloc[i,j]=(new_gen.columns[j]==gen.iloc[i,:]).sum()

In [81]:
new_gen

,War,Music,Comedy,Action,Adventure,TV Movie,Drama,History,unknown,Family,...,Foreign,Thriller,Mystery,Crime,Animation,Horror,Science Fiction,Documentary,Romance,Fantasy
0,0,0,1,0,0,0,0,0,6,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,1,0,0,0,1,0,3,1,...,0,0,0,0,0,0,0,0,1,0
2,0,0,0,0,0,0,1,0,6,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,1,0,5,0,...,0,1,0,0,0,0,0,0,0,0
4,0,0,0,1,0,0,0,0,5,0,...,0,1,0,0,0,0,0,0,0,0
5,0,0,0,0,1,0,0,0,4,1,...,0,0,0,0,1,0,0,0,0,0
6,0,0,0,0,0,0,0,0,5,0,...,0,1,0,0,0,1,0,0,0,0
7,0,0,0,0,0,0,0,0,6,0,...,0,0,0,0,0,0,0,1,0,0
8,0,1,1,1,1,0,0,0,2,1,...,0,0,0,0,0,0,0,0,0,0
9,0,1,1,0,0,0,0,0,5,0,...,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,1,0,6,0,...,0,0,0,0,0,0,0,0,0,0
11,0,0,1,0,0,0,0,0,6,0,...,0,0,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,1,0,6,0,...,0,0,0,0,0,0,0,0,0,0
13,0,0,1,0,0,0,0,0,5,0,...,0,0,0,1,0,0,0,0,0,0
14,0,0,0,1,0,0,0,0,3,0,...,0,1,1,0,0,0,1,0,0,0
15,0,0,0,1,0,0,1,0,4,0,...,0,0,0,1,0,0,0,0,0,0
16,0,0,0,0,0,0,0,0,5,0,...,0,1,0,0,0,1,0,0,0,0
17,0,0,0,0,0,0,1,0,5,0,...,0,0,0,0,0,0,0,0,1,0
18,0,0,1,0,0,0,0,0,5,0,...,0,0,0,0,0,0,0,0,1,0
19,0,0,0,1,0,0,0,0,4,0,...,0,1,0,1,0,0,0,0,0,0
20,0,0,0,0,1,0,0,0,4,1,...,0,0,0,0,0,0,1,0,0,0
21,0,0,0,0,0,0,0,0,5,0,...,0,1,0,0,0,1,0,0,0,0
22,0,0,0,0,0,0,0,0,5,0,...,0,1,0,0,0,1,0,0,0,0
23,0,0,0,0,0,0,0,0,4,0,...,1,1,1,0,0,0,0,0,0,0
24,0,0,1,0,0,0,0,0,5,0,...,0,0,0,0,0,1,0,0,0,0
25,0,0,1,0,0,0,0,0,3,0,...,0,1,1,0,0,1,0,0,0,0
26,0,0,0,0,0,0,1,0,3,0,...,0,1,1,1,0,0,0,0,0,0
27,0,0,1,0,0,0,1,0,4,0,...,0,0,0,0,0,0,0,0,1,0
28,0,0,0,0,0,0,0,0,6,0,...,0,0,0,0,1,0,0,0,0,0
29,0,0,0,1,1,0,0,0,3,0,...,0,1,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2970,0,1,0,1,0,0,1,0,2,0,...,0,1,0,0,0,0,0,0,1,0
2971,0,0,1,0,0,0,0,0,3,0,...,0,0,0,0,0,0,1,0,1,1
2972,0,0,0,1,0,0,0,0,5,0,...,0,1,0,0,0,0,0,0,0,0
2973,0,0,1,0,0,0,0,0,3,1,...,0,0,0,0,0,0,1,0,0,1
2974,0,0,0,1,0,0,0,0,3,0,...,0,1,0,0,0,1,0,0,0,1
2975,0,0,1,0,1,0,0,0,2,1,...,0,0,0,0,0,0,1,0,0,1
2976,0,0,1,0,0,0,0,0,4,0,...,0,0,1,1,0,0,0,0,0,0
2977,0,0,0,0,0,0,1,0,4,0,...,0,1,0,0,0,0,0,0,1,0
2978,0,1,0,0,0,0,1,0,5,0,...,0,0,0,0,0,0,0,0,0,0
2979,0,0,1,0,0,0,0,0,5,0,...,0,0,0,0,0,0,0,0,1,0
2980,0,0,1,1,0,0,0,0,4,0,...,0,0,0,1,0,0,0,0,0,0
2981,0,0,0,0,0,0,1,0,6,0,...,0,0,0,0,0,0,0,0,0,0
2982,0,0,0,0,0,0,1,0,6,0,...,0,0,0,0,0,0,0,0,0,0
2983,0,0,0,0,0,0,1,0,5,0,...,0,0,0,0,0,0,0,0,1,0
2984,0,0,0,1,0,0,0,0,4,0,...,0,1,0,1,0,0,0,0,0,0
2985,0,0,0,0,0,0,1,0,3,0,...,0,1,1,1,0,0,0,0,0,0
2986,0,0,0,1,0,0,1,0,4,0,...,0,1,0,0,0,0,0,0,0,0
2987,0,0,0,0,0,0,0,0,5,0,...,0,0,0,0,0,1,1,0,0,0
2988,0,0,0,0,0,0,1,0,6,0,...,0,0,0,0,0,0,0,0,0,0
2989,0,0,0,0,0,0,0,0,5,1,...,0,0,0,0,1,0,0,0,0,0
2990,0,0,1,1,0,0,0,0,5,0,...,0,0,0,0,0,0,0,0,0,0
2991,0,1,0,0,0,0,1,0,3,1,...,0,0,0,0,0,0,0,0,1,0
2992,0,0,0,1,1,0,1,0,2,1,...,0,0,0,0,0,0,0,0,0,1
2993,0,0,1,0,0,0,1,0,5,0,...,0,0,0,0,0,0,0,0,0,0
2994,0,0,0,0,0,0,1,0,6,0,...,0,0,0,0,0,0,0,0,0,0
2995,0,0,1,0,0,0,0,0,5,0,...,0,0,0,0,0,0,0,0,1,0
2996,0,1,0,0,0,0,1,0,5,0,...,0,0,0,0,0,0,0,0,0,0
2997,0,0,0,1,0,0,0,0,3,0,...,0,1,1,1,0,0,0,0,0,0
2998,0,0,1,0,0,0,0,0,5,0,...,0,0,0,0,0,0,0,0,1,0
2999,0,0,0,1,0,0,0,0,4,0,...,0,1,1,0,0,0,0,0,0,0

In [82]:
new_gen.drop(['unknown'],inplace=True,axis=1)

In [83]:
new_gen.to_csv('new_gen',index=False)

In [85]:
train.drop(['belongs_to_collection','homepage','imdb_id','original_title','poster_path','title','genres'],inplace=True,axis=1)

In [86]:
train=pd.concat([train,new_gen],axis=1)

In [491]:
from textblob import TextBlob

In [100]:
text1 = " This is a bad phone and pathetic for gamers. However, i think this should be useful for simple users."

In [101]:
blob=TextBlob(text1)

In [102]:
blob.sentiment.polarity

-0.3499999999999999

In [103]:
for i in blob.sentences:
    print(i.sentiment.polarity)

-0.8499999999999999
0.15

In [89]:
train['overview'].fillna('unknown',inplace=True)

In [90]:
ov=[]
for i in range(0,train.shape[0]):
    blob=TextBlob(train['overview'][i])
    ov.append(blob.sentiment.polarity)

In [91]:
len(ov)

3000

In [92]:
train.insert(6,'movie_sentiment',ov)

In [93]:
train.drop(['overview'],inplace=True,axis=1)

In [370]:
train.drop(['production_companies'],inplace=True,axis=1)

In [94]:
train

,id,budget,original_language,popularity,production_companies,movie_sentiment,production_countries,release_date,runtime,spoken_languages,...,Foreign,Thriller,Mystery,Crime,Animation,Horror,Science Fiction,Documentary,Romance,Fantasy
0,1,14000000,en,6.575393,"[{'name': 'Paramount Pictures', 'id': 4}, {'na...",-0.100000,"[{'iso_3166_1': 'US', 'name': 'United States o...",2/20/15,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",...,0,0,0,0,0,0,0,0,0,0
1,2,40000000,en,8.248895,"[{'name': 'Walt Disney Pictures', 'id': 2}]",0.017063,"[{'iso_3166_1': 'US', 'name': 'United States o...",8/6/04,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",...,0,0,0,0,0,0,0,0,1,0
2,3,3300000,en,64.299990,"[{'name': 'Bold Films', 'id': 2266}, {'name': ...",-0.066667,"[{'iso_3166_1': 'US', 'name': 'United States o...",10/10/14,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",...,0,0,0,0,0,0,0,0,0,0
3,4,1200000,hi,3.174936,NaN,0.022222,"[{'iso_3166_1': 'IN', 'name': 'India'}]",3/9/12,122.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",...,0,1,0,0,0,0,0,0,0,0
4,5,0,ko,1.148070,NaN,0.000000,"[{'iso_3166_1': 'KR', 'name': 'South Korea'}]",2/5/09,118.0,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",...,0,1,0,0,0,0,0,0,0,0
5,6,8000000,en,0.743274,NaN,-0.250000,NaN,8/6/87,83.0,"[{'iso_639_1': 'en', 'name': 'English'}]",...,0,0,0,0,1,0,0,0,0,0
6,7,14000000,en,7.286477,"[{'name': 'Ghost House Pictures', 'id': 768}, ...",-0.133333,"[{'iso_3166_1': 'US', 'name': 'United States o...",8/30/12,92.0,"[{'iso_639_1': 'en', 'name': 'English'}]",...,0,1,0,0,0,1,0,0,0,0
7,8,0,en,1.949044,NaN,0.216667,NaN,1/15/04,84.0,"[{'iso_639_1': 'ar', 'name': 'العربية'}, {'iso...",...,0,0,0,0,0,0,0,1,0,0
8,9,0,en,6.902423,"[{'name': 'Walt Disney Pictures', 'id': 2}, {'...",-0.022222,"[{'iso_3166_1': 'US', 'name': 'United States o...",2/16/96,100.0,"[{'iso_639_1': 'en', 'name': 'English'}]",...,0,0,0,0,0,0,0,0,0,0
9,10,6000000,en,4.672036,"[{'name': 'Castle Rock Entertainment', 'id': 97}]",0.307273,"[{'iso_3166_1': 'US', 'name': 'United States o...",4/16/03,91.0,"[{'iso_639_1': 'en', 'name': 'English'}]",...,0,0,0,0,0,0,0,0,0,0
10,11,1000000,en,14.774066,"[{'name': 'United Artists', 'id': 60}]",0.200000,"[{'iso_3166_1': 'US', 'name': 'United States o...",11/21/76,119.0,"[{'iso_639_1': 'en', 'name': 'English'}]",...,0,0,0,0,0,0,0,0,0,0
11,12,0,en,10.543750,[{'name': 'Twentieth Century Fox Film Corporat...,0.312500,"[{'iso_3166_1': 'US', 'name': 'United States o...",7/10/87,98.0,"[{'iso_639_1': 'en', 'name': 'English'}]",...,0,0,0,0,0,0,0,0,0,0
12,13,15000000,en,20.726578,"[{'name': 'DreamWorks SKG', 'id': 27}, {'name'...",0.400000,"[{'iso_3166_1': 'US', 'name': 'United States o...",9/15/99,122.0,"[{'iso_639_1': 'en', 'name': 'English'}]",...,0,0,0,0,0,0,0,0,0,0
13,14,53000000,en,13.314233,"[{'name': 'Double Feature Films', 'id': 215}, ...",-0.100000,"[{'iso_3166_1': 'US', 'name': 'United States o...",3/4/05,118.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",...,0,0,0,1,0,0,0,0,0,0
14,15,102000000,en,20.666063,"[{'name': 'DreamWorks SKG', 'id': 27}, {'name'...",0.500000,"[{'iso_3166_1': 'US', 'name': 'United States o...",6/20/02,145.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",...,0,1,1,0,0,0,1,0,0,0
15,16,500000,sr,1.018477,"[{'name': 'Hypnopolis', 'id': 51316}]",0.160000,"[{'iso_3166_1': 'RS', 'name': 'Serbia'}]",10/6/10,97.0,"[{'iso_639_1': 'sr', 'name': 'Srpski'}]",...,0,0,0,1,0,0,0,0,0,0
16,17,26000000,en,6.336927,"[{'name': 'DreamWorks SKG', 'id': 27}, {'name'...",-0.203571,"[{'iso_3166_1': 'US', 'name': 'United States o...",8/4/05,85.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",...,0,1,0,0,0,1,0,0,0,0
17,18,0,en,4.183558,"[{'name': 'BBC Films', 'id': 288}, {'name': 'H...",-0.041667,"[{'iso_3166_1': 'GB', 'name': 'United Kingdom'}]",12/25/13,111.0,"[{'iso_639_1': 'en', 'name': 'English'}]",...,0,0,0,0,0,0,0,0,1,0
18,19,8000000,en,6.496259,"[{'name': 'UK Film Council', 'id': 2452}, {'na...",0.220000,"[{'iso_3166_1': 'AT', 'name': 'Austria'}, {'is...",2/2/11,96.0,"[{'iso_639_1': 'de', 'name': 'Deutsch'}, {'iso...",...,0,0,0,0,0,0,0,0,1,0
19,20,32000000,en,11.359659,[{'name': 'Twentieth Century Fox Film Corporat...,0.100000,"[{'iso_3166_1': 'FR', 'name': 'France'}]",8/2/05,87.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",...,0,1,0,1,0,0,0,0,0,0
20,21,80000000,en,12.000579,"[{'name': 'New Line Cinema', 'id': 12}, {'name...",-0.375000,"[{'iso_3166_1': 'US', 'name': 'United States o...",4/3/98,130.0,"[{'iso_639_1': 'en', 'name': 'English'}]",...,0,0,0,0,0,0,1,0,0,0
21,22,4000000,en,7.992290,"[{'name': 'Paramount Pictures', 'id': 4}, {'na...",-0.391667,"[{'iso_3166_1': 'US', 'name': 'United States o...",8/13/82,95.0,"[{'iso_639_1': 'en', 'name': 'English'}]",...,0,1,0,0,0,1,0,0,0,0
22,23,0,en,7.820787,"[{'name': 'The Collective', 'id': 15156}, {'na...",0.175000,"[{'iso_3166_1': 'US', 'name': 'United States o...",7/28/12,116.0,"[{'iso_639_1': 'en', 'name': 'English'}]",...,0,1,0,0,0,1,0,0,0,0
23,24,0,en,1.323333,"[{'name': '\xa0Braeburn Entertainment', 'id': ...",-0.139524,"[{'iso_3166_1': 'US', 'name': 'United States o...",9/2/11,92.0,"[{'iso_639_1': 'en', 'name': 'English'}]",...,1,1,1,0,0,0,0,0,0,0
24,25,0,en,7.434577,"[{'name': 'New Zealand Film Commission', 'id':...",-0.107143,"[{'iso_3166_1': 'NZ', 'name': 'New Zealand'}]",9/9/06,87.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",...,0,0,0,0,0,1,0,0,0,0
25,26,0,en,1.252367,"[{'name': 'Universal Pictures', 'id': 33}, {'n...",-0.035000,"[{'iso_3166_1': 'JP', 'name': 'Japan'}, {'iso_...",10/23/92,95.0,"[{'iso_639_1': 'en', 'name': 'English'}]",...,0,1,1,0,0,1,0,0,0,0
26,27,10000000,en,4.305735,"[{'name': 'Jean Doumanian Productions', 'id': ...",0.050000,"[{'iso_3166_1': 'US', 'name': 'United States o...",9/8/97,110.0,"[{'iso_639_1': 'en', 'name': 'English'}]",...,0,1,1,1,0,0,0,0,0,0
27,28,11000000,en,10.841891,"[{'name': 'Fastnet Films', 'id': 5353}, {'name...",0.275000,"[{'iso_3166_1': 'CA', 'name': 'Canada'}, {'iso...",9/7/13,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",...,0,0,0,0,0,0,0,0,1,0
28,29,6000000,en,6.759181,[{'name': 'De Laurentiis Entertainment Group (...,0.150000,"[{'iso_3166_1': 'US', 'name': 'United States o...",8/8/86,84.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",...,0,0,0,0,1,0,0,0,0,0
29,30,45000000,en,7.818620,"[{'name': 'Paramount Pictures', 'id': 4}]",-0.069421,"[{'iso_3166_1': 'US', 'name': 'United States o...",4/7/02,89.0,"[{'iso_639_1': 'en', 'name': 'English'}]",...,0,1,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2970,2971,25000000,en,9.805017,"[{'name': 'Tig Productions', 'id': 335}, {'nam...",-0.169841,"[{'iso_3166_1': 'US', 'name': 'United States o...",11/25/92,129.0,"[{'iso_639_1': 'en', 'name': 'English'}]",...,0,1,0,0,0,0,0,0,1,0
2971,2972,20000000,en,4.414928,"[{'name': 'Touchstone Pictures', 'id': 9195}]",-0.194805,"[{'iso_3166_1': 'US', 'name': 'United States o...",10/12/90,110.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",...,0,0,0,0,0,0,1,0,1,1
2972,2973,0,cn,4.154861,[{'name': 'China Film Co-Production Corporatio...,0.150000,"[{'iso_3166_1': 'CN', 'name': 'China'}, {'iso_...",7/27/06,94.0,"[{'iso_639_1': 'cn', 'name': '广州话 / 廣州話'}]",...,0,1,0,0,0,0,0,0,0,0
2973,2974,0,en,3.868014,"[{'name': 'Touchstone Pictures', 'id': 9195}, ...",-0.080000,"[{'iso_3166_1': 'US', 'name': 'United States o...",8/9/85,94.0,"[{'iso_639_1': 'en', 'name': 'English'}]",...,0,0,0,0,0,0,1,0,0,1
2974,2975,20000000,en,5.871243,[{'name': 'Boll Kino Beteiligungs GmbH & Co. K...,0.095238,"[{'iso_3166_1': 'CA', 'name': 'Canada'}, {'iso...",1/28/05,96.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",...,0,1,0,0,0,1,0,0,0,1
2975,2976,45000000,en,11.618472,[{'name': 'Twentieth Century Fox Film Corporat...,-0.107813,"[{'iso_3166_1': 'CA', 'name': 'Canada'}, {'iso...",7/31/09,86.0,"[{'iso_639_1': 'en', 'name': 'English'}]",...,0,0,0,0,0,0,1,0,0,1
2976,2977,16000000,en,4.372616,"[{'name': 'Code Entertainment', 'id': 14589}, ...",-0.016667,"[{'iso_3166_1': 'US', 'name': 'United States o...",3/3/00,96.0,"[{'iso_639_1': 'en', 'name': 'English'}]",...,0,0,1,1,0,0,0,0,0,0
2977,2978,53000000,en,5.396200,"[{'name': 'Epsilon Motion Pictures', 'id': 117...",-0.156250,"[{'iso_3166_1': 'US', 'name': 'United States o...",5/15/01,102.0,"[{'iso_639_1': 'en', 'name': 'English'}]",...,0,1,0,0,0,0,0,0,1,0
2978,2979,0,en,16.529300,"[{'name': 'Channel Four Films', 'id': 181}, {'...",0.278788,"[{'iso_3166_1': 'GB', 'name': 'United Kingdom'}]",10/23/98,119.0,"[{'iso_639_1': 'en', 'name': 'English'}]",...,0,0,0,0,0,0,0,0,0,0
2979,2980,35000000,en,6.629999,"[{'name': 'Escape Artists', 'id': 1423}, {'nam...",0.112143,"[{'iso_3166_1': 'US', 'name': 'United States o...",4/23/10,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",...,0,0,0,0,0,0,0,0,1,0
2980,2981,300000,ml,0.350207,"[{'name': 'Full On Studios', 'id': 73777}, {'n...",0.241667,"[{'iso_3166_1': 'IN', 'name': 'India'}]",2/4/16,144.0,"[{'iso_639_1': 'ml', 'name': ''}]",...,0,0,0,1,0,0,0,0,0,0
2981,2982,0,en,3.069108,"[{'name': 'Park Pictures', 'id': 13466}, {'nam...",-0.161132,"[{'iso_3166_1': 'US', 'name': 'United States o...",9/9/16,97.0,"[{'iso_639_1': 'en', 'name': 'English'}]",...,0,0,0,0,0,0,0,0,0,0
2982,2983,500000,en,4.893812,"[{'name': 'Super Crispy Entertainment', 'id': ...",0.416667,"[{'iso_3166_1': 'US', 'name': 'United States o...",9/12/12,85.0,"[{'iso_639_1': 'en', 'name': 'English'}]",...,0,0,0,0,0,0,0,0,0,0
2983,2984,35000000,en,5.660835,"[{'name': 'Icon Entertainment International', ...",0.500000,"[{'iso_3166_1': 'US', 'name': 'United States o...",4/4/97,108.0,"[{'iso_639_1': 'en', 'name': 'English'}]",...,0,0,0,0,0,0,0,0,1,0
2984,2985,80000000,en,13.334952,"[{'name': 'Original Film', 'id': 333}, {'name'...",0.132187,"[{'iso_3166_1': 'US', 'name': 'United States o...",8/8/03,117.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",...,0,1,0,1,0,0,0,0,0,0
2985,2986,37665000,en,5.388535,"[{'name': 'Scott Rudin Productions', 'id': 258...",-0.072222,"[{'iso_3166_1': 'US', 'name': 'United States o...",2/17/06,113.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",...,0,1,1,1,0,0,0,0,0,0
2986,2987,20000000,en,12.553403,"[{'name': 'Icon Productions', 'id': 152}, {'na...",0.000000,"[{'iso_3166_1': 'US', 'name': 'United States o...",9/3/04,84.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",...,0,1,0,0,0,0,0,0,0,0
2987,2988,0,en,1.292125,"[{'name': 'Concorde Pictures', 'id': 4527}]",-0.266667,"[{'iso_3166_1': 'US', 'name': 'United States o...",1/20/89,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",...,0,0,0,0,0,1,1,0,0,0
2988,2989,0,fa,0.984515,"[{'name': 'Abbas Kiarostami Productions', 'id'...",0.008333,"[{'iso_3166_1': 'IR', 'name': 'Iran'}]",5/20/02,94.0,"[{'iso_639_1': 'fa', 'name': 'فارسی'}]",...,0,0,0,0,0,0,0,0,0,0
2989,2990,0,en,0.851599,"[{'name': 'TriStar Pictures', 'id': 559}, {'na...",0.315000,"[{'iso_3166_1': 'US', 'name': 'United States o...",5/11/01,75.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",...,0,0,0,0,1,0,0,0,0,0
2990,2991,0,en,1.560980,"[{'name': 'New Line Cinema', 'id': 12}, {'name...",0.088889,NaN,3/28/97,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",...,0,0,0,0,0,0,0,0,0,0
2991,2992,13000000,en,4.794088,"[{'name': 'MTV Films', 'id': 746}, {'name': 'C...",-0.063384,"[{'iso_3166_1': 'US', 'name': 'United States o...",1/12/01,112.0,"[{'iso_639_1': 'en', 'name': 'English'}]",...,0,0,0,0,0,0,0,0,1,0
2992,2993,1135654,en,3.878515,"[{'name': 'Douglas Fairbanks Pictures', 'id': ...",0.850000,"[{'iso_3166_1': 'US', 'name': 'United States o...",3/18/24,149.0,"[{'iso_639_1': 'xx', 'name': 'No Language'}]",...,0,0,0,0,0,0,0,0,0,1
2993,2994,60000000,en,14.092373,"[{'name': 'DreamWorks SKG', 'id': 27}, {'name'...",0.350000,"[{'iso_3166_1': 'US', 'name': 'United States o...",6/17/04,128.0,"[{'iso_639_1': 'bg', 'name': 'български език'}...",...,0,0,0,0,0,0,0,0,0,0
2994,2995,0,en,7.438381,"[{'name': 'Paramount Pictures', 'id': 4}]",-0.158333,"[{'iso_3166_1': 'US', 'name': 'United States o...",9/18/92,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",...,0,0,0,0,0,0,0,0,0,0
2995,2996,0,en,9.853270,"[{'name': 'Warner Bros.', 'id': 6194}, {'name'...",0.216667,"[{'iso_3166_1': 'US', 'name': 'United States o...",4/22/94,102.0,"[{'iso_639_1': 'en', 'name': 'English'}]",...,0,0,0,0,0,0,0,0,1,0
2996,2997,0,sv,3.727996,"[{'name': 'Memfis Film', 'id': 321}, {'name': ...",-0.200000,"[{'iso_3166_1': 'DK', 'name': 'Denmark'}, {'is...",3/28/13,102.0,"[{'iso_639_1': 'sv', 'name': 'svenska'}]",...,0,0,0,0,0,0,0,0,0,0
2997,2998,65000000,en,14.482345,"[{'name': 'New Line Cinema', 'id': 12}, {'name...",0.263889,"[{'iso_3166_1': 'US', 'name': 'United States o...",10/11/96,120.0,"[{'iso_639_1': 'en', 'name': 'English'}]",...,0,1,1,1,0,0,0,0,0,0
2998,2999,42000000,en,15.725542,"[{'name': 'Jersey Films', 'id': 216}, {'name':...",0.148889,"[{'iso_3166_1': 'US', 'name': 'United States o...",1/16/04,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",...,0,0,0,0,0,0,0,0,1,0
2999,3000,35000000,en,10.512109,"[{'name': 'Lions Gate Films', 'id': 35}, {'nam...",-0.050000,"[{'iso_3166_1': 'US', 'name': 'United States o...",9/22/11,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",...,0,1,1,0,0,0,0,0,0,0

In [95]:
train.to_csv('train_c',index=False)

In [371]:
pc=train['production_countries'].str.split(',',n=100,expand=True)

In [373]:
pc=pc.iloc[:,[1,3,5,7,9,11,13,15]]

In [381]:
pc.loc[:,15].notnull().sum()

1

In [384]:
pc.fillna('unknown',inplace=True)

C:\Users\LENOVO\Anaconda3\lib\site-packages\pandas\core\frame.py:4034: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  downcast=downcast, **kwargs)

In [385]:
pc

,1,3,5,7,9,11,13,15
0,'name': 'United States of America'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown
1,'name': 'United States of America'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown
2,'name': 'United States of America'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown
3,'name': 'India'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown
4,'name': 'South Korea'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown
5,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
6,'name': 'United States of America'},'name': 'Canada'}],unknown,unknown,unknown,unknown,unknown,unknown
7,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
8,'name': 'United States of America'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown
9,'name': 'United States of America'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown
10,'name': 'United States of America'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown
11,'name': 'United States of America'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown
12,'name': 'United States of America'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown
13,'name': 'United States of America'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown
14,'name': 'United States of America'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown
15,'name': 'Serbia'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown
16,'name': 'United States of America'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown
17,'name': 'United Kingdom'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown
18,'name': 'Austria'},'name': 'Germany'},'name': 'United Kingdom'}],unknown,unknown,unknown,unknown,unknown
19,'name': 'France'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown
20,'name': 'United States of America'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown
21,'name': 'United States of America'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown
22,'name': 'United States of America'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown
23,'name': 'United States of America'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown
24,'name': 'New Zealand'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown
25,'name': 'Japan'},'name': 'United States of America'}],unknown,unknown,unknown,unknown,unknown,unknown
26,'name': 'United States of America'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown
27,'name': 'Canada'},'name': 'Ireland'}],unknown,unknown,unknown,unknown,unknown,unknown
28,'name': 'United States of America'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown
29,'name': 'United States of America'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown
...,...,...,...,...,...,...,...,...
2970,'name': 'United States of America'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown
2971,'name': 'United States of America'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown
2972,'name': 'China'},'name': 'Hong Kong'}],unknown,unknown,unknown,unknown,unknown,unknown
2973,'name': 'United States of America'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown
2974,'name': 'Canada'},'name': 'Germany'},'name': 'United States of America'}],unknown,unknown,unknown,unknown,unknown
2975,'name': 'Canada'},'name': 'United States of America'}],unknown,unknown,unknown,unknown,unknown,unknown
2976,'name': 'United States of America'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown
2977,'name': 'United States of America'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown
2978,'name': 'United Kingdom'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown
2979,'name': 'United States of America'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown
2980,'name': 'India'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown
2981,'name': 'United States of America'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown
2982,'name': 'United States of America'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown
2983,'name': 'United States of America'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown
2984,'name': 'United States of America'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown
2985,'name': 'United States of America'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown
2986,'name': 'United States of America'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown
2987,'name': 'United States of America'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown
2988,'name': 'Iran'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown
2989,'name': 'United States of America'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown
2990,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2991,'name': 'United States of America'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown
2992,'name': 'United States of America'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown
2993,'name': 'United States of America'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown
2994,'name': 'United States of America'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown
2995,'name': 'United States of America'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown
2996,'name': 'Denmark'},'name': 'Sweden'}],unknown,unknown,unknown,unknown,unknown,unknown
2997,'name': 'United States of America'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown
2998,'name': 'United States of America'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown
2999,'name': 'United States of America'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown

In [386]:
for j in range(0,pc.shape[1]):
    pc1=pc.iloc[:,j]
    import re
    for i in range(0,pc1.shape[0]):
        m=re.search(': (.+?)}',pc1[i])
        if m:
            found=m.group(1)
            pc1[i]=found[1:-1]

In [387]:
pc

,1,3,5,7,9,11,13,15
0,United States of America,unknown,unknown,unknown,unknown,unknown,unknown,unknown
1,United States of America,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2,United States of America,unknown,unknown,unknown,unknown,unknown,unknown,unknown
3,India,unknown,unknown,unknown,unknown,unknown,unknown,unknown
4,South Korea,unknown,unknown,unknown,unknown,unknown,unknown,unknown
5,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
6,United States of America,Canada,unknown,unknown,unknown,unknown,unknown,unknown
7,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
8,United States of America,unknown,unknown,unknown,unknown,unknown,unknown,unknown
9,United States of America,unknown,unknown,unknown,unknown,unknown,unknown,unknown
10,United States of America,unknown,unknown,unknown,unknown,unknown,unknown,unknown
11,United States of America,unknown,unknown,unknown,unknown,unknown,unknown,unknown
12,United States of America,unknown,unknown,unknown,unknown,unknown,unknown,unknown
13,United States of America,unknown,unknown,unknown,unknown,unknown,unknown,unknown
14,United States of America,unknown,unknown,unknown,unknown,unknown,unknown,unknown
15,Serbia,unknown,unknown,unknown,unknown,unknown,unknown,unknown
16,United States of America,unknown,unknown,unknown,unknown,unknown,unknown,unknown
17,United Kingdom,unknown,unknown,unknown,unknown,unknown,unknown,unknown
18,Austria,Germany,United Kingdom,unknown,unknown,unknown,unknown,unknown
19,France,unknown,unknown,unknown,unknown,unknown,unknown,unknown
20,United States of America,unknown,unknown,unknown,unknown,unknown,unknown,unknown
21,United States of America,unknown,unknown,unknown,unknown,unknown,unknown,unknown
22,United States of America,unknown,unknown,unknown,unknown,unknown,unknown,unknown
23,United States of America,unknown,unknown,unknown,unknown,unknown,unknown,unknown
24,New Zealand,unknown,unknown,unknown,unknown,unknown,unknown,unknown
25,Japan,United States of America,unknown,unknown,unknown,unknown,unknown,unknown
26,United States of America,unknown,unknown,unknown,unknown,unknown,unknown,unknown
27,Canada,Ireland,unknown,unknown,unknown,unknown,unknown,unknown
28,United States of America,unknown,unknown,unknown,unknown,unknown,unknown,unknown
29,United States of America,unknown,unknown,unknown,unknown,unknown,unknown,unknown
...,...,...,...,...,...,...,...,...
2970,United States of America,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2971,United States of America,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2972,China,Hong Kong,unknown,unknown,unknown,unknown,unknown,unknown
2973,United States of America,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2974,Canada,Germany,United States of America,unknown,unknown,unknown,unknown,unknown
2975,Canada,United States of America,unknown,unknown,unknown,unknown,unknown,unknown
2976,United States of America,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2977,United States of America,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2978,United Kingdom,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2979,United States of America,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2980,India,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2981,United States of America,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2982,United States of America,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2983,United States of America,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2984,United States of America,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2985,United States of America,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2986,United States of America,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2987,United States of America,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2988,Iran,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2989,United States of America,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2990,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2991,United States of America,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2992,United States of America,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2993,United States of America,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2994,United States of America,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2995,United States of America,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2996,Denmark,Sweden,unknown,unknown,unknown,unknown,unknown,unknown
2997,United States of America,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2998,United States of America,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2999,United States of America,unknown,unknown,unknown,unknown,unknown,unknown,unknown

In [423]:
unique_pc=pc.loc[:,1].value_counts()

In [424]:
unique_pc=pd.DataFrame(unique_pc)

In [429]:
unique_pc=unique_pc.index[0:20]

In [432]:
unique_pc

Index(['United States of America', 'United Kingdom', 'France', 'Canada',
       'Germany', 'India', 'unknown', 'Australia', 'Japan', 'Russia', 'Italy',
       'China', 'Spain', 'Hong Kong', 'Mexico', 'South Korea', 'Ireland',
       'Belgium', 'New Zealand', 'Brazil'],
      dtype='object')

In [433]:
new_pc=pd.DataFrame(columns=unique_pc,index=np.arange(0,3000,1))

In [434]:
for j in range(0,len(new_pc.columns)):
    for i in range(0,pc.shape[0]):
        new_pc.iloc[i,j]=(new_pc.columns[j]==pc.iloc[i,:]).sum()

In [436]:
new_pc.drop(['unknown'],inplace=True,axis=1)

In [437]:
new_pc

,United States of America,United Kingdom,France,Canada,Germany,India,Australia,Japan,Russia,Italy,China,Spain,Hong Kong,Mexico,South Korea,Ireland,Belgium,New Zealand,Brazil
0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
6,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
8,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
9,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
11,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
12,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
13,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
14,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
15,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
16,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
17,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
18,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
19,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
20,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
21,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
22,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
23,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
24,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
25,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
26,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
27,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
28,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
29,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2970,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2971,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2972,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0
2973,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2974,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2975,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2976,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2977,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2978,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2979,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2980,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
2981,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2982,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2983,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2984,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2985,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2986,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2987,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2988,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2989,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2990,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2991,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2992,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2993,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2994,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2995,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2996,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2997,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2998,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2999,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [438]:
train=pd.concat([train,new_pc],axis=1)

In [440]:
train.drop(['production_countries'],inplace=True,axis=1)

In [441]:
train.to_csv('train_c1')

In [444]:
sl=train['spoken_languages'].str.split(',',n=100,expand=True)

In [446]:
sl=sl.iloc[:,[1,3,5,7,9,11,13,15,17]]

In [452]:
sl.loc[:,17].notnull().sum()

1

In [453]:
sl.fillna('unknown',inplace=True)

,1,3,5,7,9,11,13,15,17
0,'name': 'English'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
1,'name': 'English'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2,'name': 'English'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
3,'name': 'English'},'name': 'हिन्दी'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown
4,'name': '한국어/조선말'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
5,'name': 'English'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
6,'name': 'English'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
7,'name': 'العربية'},'name': 'English'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown
8,'name': 'English'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
9,'name': 'English'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
10,'name': 'English'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
11,'name': 'English'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
12,'name': 'English'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
13,'name': 'English'},'name': 'Pусский'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown
14,'name': 'English'},'name': 'svenska'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown
15,'name': 'Srpski'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
16,'name': 'English'},'name': 'Pусский'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown
17,'name': 'English'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
18,'name': 'Deutsch'},'name': 'English'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown
19,'name': 'English'},'name': 'Français'},'name': 'Italiano'}],unknown,unknown,unknown,unknown,unknown,unknown
20,'name': 'English'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
21,'name': 'English'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
22,'name': 'English'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
23,'name': 'English'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
24,'name': 'English'},'name': 'Français'},'name': 'Italiano'}],unknown,unknown,unknown,unknown,unknown,unknown
25,'name': 'English'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
26,'name': 'English'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
27,'name': 'English'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
28,'name': 'English'},'name': '日本語'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown
29,'name': 'English'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
...,...,...,...,...,...,...,...,...,...
2970,'name': 'English'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2971,'name': 'English'},'name': 'Magyar'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown
2972,'name': '广州话 / 廣州話'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2973,'name': 'English'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2974,'name': 'English'},'name': 'Português'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown
2975,'name': 'English'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2976,'name': 'English'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2977,'name': 'English'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2978,'name': 'English'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2979,'name': 'English'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2980,'name': ''}],unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2981,'name': 'English'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2982,'name': 'English'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2983,'name': 'English'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2984,'name': 'English'},'name': 'Español'},'name': 'Français'}],unknown,unknown,unknown,unknown,unknown,unknown
2985,'name': 'English'},'name': 'Italiano'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown
2986,'name': 'English'},'name': 'Español'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown
2987,'name': 'English'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2988,'name': 'فارسی'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2989,'name': 'English'},'name': 'Français'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown
2990,'name': 'English'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2991,'name': 'English'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2992,'name': 'No Language'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2993,'name': 'български език'},'name': 'English'},'name': 'Français'},'name': 'Pусский'},'name': 'Español'}],unknown,unknown,unknown,unknown
2994,'name': 'English'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2995,'name': 'English'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2996,'name': 'svenska'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2997,'name': 'English'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2998,'name': 'English'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2999,'name': 'English'}],unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown

In [455]:
for j in range(0,sl.shape[1]):
    sl1=sl.iloc[:,j]
    import re
    for i in range(0,sl1.shape[0]):
        m=re.search(': (.+?)}',sl1[i])
        if m:
            found=m.group(1)
            sl1[i]=found[1:-1]

In [456]:
sl

,1,3,5,7,9,11,13,15,17
0,English,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
1,English,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2,English,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
3,English,हिन्दी,unknown,unknown,unknown,unknown,unknown,unknown,unknown
4,한국어/조선말,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
5,English,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
6,English,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
7,العربية,English,unknown,unknown,unknown,unknown,unknown,unknown,unknown
8,English,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
9,English,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
10,English,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
11,English,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
12,English,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
13,English,Pусский,unknown,unknown,unknown,unknown,unknown,unknown,unknown
14,English,svenska,unknown,unknown,unknown,unknown,unknown,unknown,unknown
15,Srpski,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
16,English,Pусский,unknown,unknown,unknown,unknown,unknown,unknown,unknown
17,English,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
18,Deutsch,English,unknown,unknown,unknown,unknown,unknown,unknown,unknown
19,English,Français,Italiano,unknown,unknown,unknown,unknown,unknown,unknown
20,English,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
21,English,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
22,English,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
23,English,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
24,English,Français,Italiano,unknown,unknown,unknown,unknown,unknown,unknown
25,English,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
26,English,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
27,English,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
28,English,日本語,unknown,unknown,unknown,unknown,unknown,unknown,unknown
29,English,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
...,...,...,...,...,...,...,...,...,...
2970,English,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2971,English,Magyar,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2972,广州话 / 廣州話,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2973,English,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2974,English,Português,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2975,English,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2976,English,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2977,English,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2978,English,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2979,English,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2980,,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2981,English,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2982,English,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2983,English,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2984,English,Español,Français,unknown,unknown,unknown,unknown,unknown,unknown
2985,English,Italiano,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2986,English,Español,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2987,English,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2988,فارسی,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2989,English,Français,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2990,English,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2991,English,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2992,No Language,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2993,български език,English,Français,Pусский,Español,unknown,unknown,unknown,unknown
2994,English,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2995,English,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2996,svenska,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2997,English,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2998,English,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2999,English,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown

In [458]:
unique_sl=sl.loc[:,1].value_counts()

In [459]:
unique_sl=pd.DataFrame(unique_sl)

In [467]:
unique_sl=unique_sl.drop(['unknown'])

In [477]:
unique_sl=unique_sl[0:27]

In [481]:
unique_sl=unique_sl.index

In [482]:
new_sl=pd.DataFrame(columns=unique_sl,index=np.arange(0,3000,1))

In [483]:
for j in range(0,len(new_sl.columns)):
    for i in range(0,sl.shape[0]):
        new_sl.iloc[i,j]=(new_sl.columns[j]==sl.iloc[i,:]).sum()

In [484]:
new_sl

,English,Français,Español,Pусский,Deutsch,日本語,हिन्दी,广州话 / 廣州話,Italiano,普通话,...,Nederlands,Dansk,No Language,Latin,فارسی,suomi,Polski,עִבְרִית,ελληνικά,Afrikaans
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,1,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,1,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,1,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,1,1,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
20,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,1,1,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
25,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,1,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2970,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2971,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2972,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2973,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2974,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2975,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2976,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2977,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2978,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2979,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2980,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2981,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2982,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2983,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2984,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2985,1,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2986,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2987,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2988,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
2989,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2990,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2991,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2992,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2993,1,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2994,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2995,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2997,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2998,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2999,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [485]:
train=pd.concat([train,new_sl],axis=1)

In [486]:
train

,id,budget,original_language,popularity,movie_sentiment,release_date,runtime,spoken_languages,status,tagline,...,Nederlands,Dansk,No Language,Latin,فارسی,suomi,Polski,עִבְרִית,ελληνικά,Afrikaans
0,1,14000000,en,6.575393,-0.100000,2/20/15,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,...,0,0,0,0,0,0,0,0,0,0
1,2,40000000,en,8.248895,0.017063,8/6/04,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,...,0,0,0,0,0,0,0,0,0,0
2,3,3300000,en,64.299990,-0.066667,10/10/14,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,...,0,0,0,0,0,0,0,0,0,0
3,4,1200000,hi,3.174936,0.022222,3/9/12,122.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,...,0,0,0,0,0,0,0,0,0,0
4,5,0,ko,1.148070,0.000000,2/5/09,118.0,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Released,NaN,...,0,0,0,0,0,0,0,0,0,0
5,6,8000000,en,0.743274,-0.250000,8/6/87,83.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,...,0,0,0,0,0,0,0,0,0,0
6,7,14000000,en,7.286477,-0.133333,8/30/12,92.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Fear The Demon That Doesn't Fear God,...,0,0,0,0,0,0,0,0,0,0
7,8,0,en,1.949044,0.216667,1/15/04,84.0,"[{'iso_639_1': 'ar', 'name': 'العربية'}, {'iso...",Released,Different channels. Different truths.,...,0,0,0,0,0,0,0,0,0,0
8,9,0,en,6.902423,-0.022222,2/16/96,100.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Set sail for Muppet mayhem!,...,0,0,0,0,0,0,0,0,0,0
9,10,6000000,en,4.672036,0.307273,4/16/03,91.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"Back together for the first time, again.",...,0,0,0,0,0,0,0,0,0,0
10,11,1000000,en,14.774066,0.200000,11/21/76,119.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,His whole life was a million-to-one shot.,...,0,0,0,0,0,0,0,0,0,0
11,12,0,en,10.543750,0.312500,7/10/87,98.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,They're Back!,...,0,0,0,0,0,0,0,0,0,0
12,13,15000000,en,20.726578,0.400000,9/15/99,122.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Look closer.,...,0,0,0,0,0,0,0,0,0,0
13,14,53000000,en,13.314233,-0.100000,3/4/05,118.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Everyone is looking for the next big hit,...,0,0,0,0,0,0,0,0,0,0
14,15,102000000,en,20.666063,0.500000,6/20/02,145.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,The system is perfect until it comes after you.,...,0,0,0,0,0,0,0,0,0,0
15,16,500000,sr,1.018477,0.160000,10/6/10,97.0,"[{'iso_639_1': 'sr', 'name': 'Srpski'}]",Released,Life is sometimes rude game: one mistake can b...,...,0,0,0,0,0,0,0,0,0,0
16,17,26000000,en,6.336927,-0.203571,8/4/05,85.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Fear takes flight.,...,0,0,0,0,0,0,0,0,0,0
17,18,0,en,4.183558,-0.041667,12/25/13,111.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,His greatest story was the one he could never ...,...,0,0,0,0,0,0,0,0,0,0
18,19,8000000,en,6.496259,0.220000,2/2/11,96.0,"[{'iso_639_1': 'de', 'name': 'Deutsch'}, {'iso...",Released,How to marry a billionaire.,...,0,0,0,0,0,0,0,0,0,0
19,20,32000000,en,11.359659,0.100000,8/2/05,87.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,The Best In The Business Is Back In The Game.,...,0,0,0,0,0,0,0,0,0,0
20,21,80000000,en,12.000579,-0.375000,4/3/98,130.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"Danger, Will Robinson!",...,0,0,0,0,0,0,0,0,0,0
21,22,4000000,en,7.992290,-0.391667,8/13/82,95.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,There's nowhere to hide. We dare you to try.,...,0,0,0,0,0,0,0,0,0,0
22,23,0,en,7.820787,0.175000,7/28/12,116.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,This collection is killer.,...,0,0,0,0,0,0,0,0,0,0
23,24,0,en,1.323333,-0.139524,9/2/11,92.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Fear what you see,...,0,0,0,0,0,0,0,0,0,0
24,25,0,en,7.434577,-0.107143,9/9/06,87.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,There are over 40 million sheep in New Zealand...,...,0,0,0,0,0,0,0,0,0,0
25,26,0,en,1.252367,-0.035000,10/23/92,95.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Doctor is out... of his mind.,...,0,0,0,0,0,0,0,0,0,0
26,27,10000000,en,4.305735,0.050000,9/8/97,110.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It's the oldest con in the book.,...,0,0,0,0,0,0,0,0,0,0
27,28,11000000,en,10.841891,0.275000,9/7/13,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,...being friends has its benefits?,...,0,0,0,0,0,0,0,0,0,0
28,29,6000000,en,6.759181,0.150000,8/8/86,84.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Beyond good. Beyond evil. Beyond your wildest ...,...,0,0,0,0,0,0,0,0,0,0
29,30,45000000,en,7.818620,-0.069421,4/7/02,89.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"An ambitious lawyer, a desperate father, they ...",...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2970,2971,25000000,en,9.805017,-0.169841,11/25/92,129.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Never let her out of your sight. Never let you...,...,0,0,0,0,0,0,0,0,0,0
2971,2972,20000000,en,4.414928,-0.194805,10/12/90,110.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Larry Burrows Wished For It All... Until All T...,...,0,0,0,0,0,0,0,0,0,0
2972,2973,0,cn,4.154861,0.150000,7/27/06,94.0,"[{'iso_639_1': 'cn', 'name': '广州话 / 廣州話'}]",Released,NaN,...,0,0,0,0,0,0,0,0,0,0
2973,2974,0,en,3.868014,-0.080000,8/9/85,94.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,We must not destroy the world.,...,0,0,0,0,0,0,0,0,0,0
2974,2975,20000000,en,5.871243,0.095238,1/28/05,96.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Can mankind defeat the army of darkness unleas...,...,0,0,0,0,0,0,0,0,0,0
2975,2976,45000000,en,11.618472,-0.107813,7/31/09,86.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The aliens vs. the Pearsons,...,0,0,0,0,0,0,0,0,0,0
2976,2977,16000000,en,4.372616,-0.016667,3/3/00,96.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The death of Mona Dearly wasn't so much a whod...,...,0,0,0,0,0,0,0,0,0,0
2977,2978,53000000,en,5.396200,-0.156250,5/15/01,102.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"The deeper you look, the more you will find.",...,0,0,0,0,0,0,0,0,0,0
2978,2979,0,en,16.529300,0.278788,10/23/98,119.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Style matters. Even when it comes to murder.,...,0,0,0,0,0,0,0,0,0,0
2979,2980,35000000,en,6.629999,0.112143,4/23/10,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"Fall in love, get married, have a baby. Not ne...",...,0,0,0,0,0,0,0,0,0,0
2980,2981,300000,ml,0.350207,0.241667,2/4/16,144.0,"[{'iso_639_1': 'ml', 'name': ''}]",Released,A ride with a police officer,...,0,0,0,0,0,0,0,0,0,0
2981,2982,0,en,3.069108,-0.161132,9/9/16,97.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,...,0,0,0,0,0,0,0,0,0,0
2982,2983,500000,en,4.893812,0.416667,9/12/12,85.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,...,0,0,0,0,0,0,0,0,0,0
2983,2984,35000000,en,5.660835,0.500000,4/4/97,108.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"In a world of power and privilege, one woman d...",...,0,0,0,0,0,0,0,0,0,0
2984,2985,80000000,en,13.334952,0.132187,8/8/03,117.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,You're either S.W.A.T. or you're not.,...,0,0,0,0,0,0,0,0,0,0
2985,2986,37665000,en,5.388535,-0.072222,2/17/06,113.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,The Truth Is Hiding Where No One Dares To Look.,...,0,0,0,0,0,0,0,0,0,0
2986,2987,20000000,en,12.553403,0.000000,9/3/04,84.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,One good shot deserves another.,...,0,0,0,0,0,0,0,0,0,0
2987,2988,0,en,1.292125,-0.266667,1/20/89,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It Wants To Get Out!,...,0,0,0,0,0,0,0,0,0,0
2988,2989,0,fa,0.984515,0.008333,5/20/02,94.0,"[{'iso_639_1': 'fa', 'name': 'فارسی'}]",Released,NaN,...,0,0,0,0,1,0,0,0,0,0
2989,2990,0,en,0.851599,0.315000,5/11/01,75.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Sometimes being different helps you to find yo...,...,0,0,0,0,0,0,0,0,0,0
2990,2991,0,en,1.560980,0.088889,3/28/97,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,These Pretty Women... Are Clueless!,...,0,0,0,0,0,0,0,0,0,0
2991,2992,13000000,en,4.794088,-0.063384,1/12/01,112.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Only Person You Need To Be Is Yourself.,...,0,0,0,0,0,0,0,0,0,0
2992,2993,1135654,en,3.878515,0.850000,3/18/24,149.0,"[{'iso_639_1': 'xx', 'name': 'No Language'}]",Released,"""Happiness Must Be Earned""",...,0,0,1,0,0,0,0,0,0,0
2993,2994,60000000,en,14.092373,0.350000,6/17/04,128.0,"[{'iso_639_1': 'bg', 'name': 'български език'}...",Released,Life is waiting.,...,0,0,0,0,0,0,0,0,0,0
2994,2995,0,en,7.438381,-0.158333,9/18/92,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just because you’re accepted doesn’t mean you ...,...,0,0,0,0,0,0,0,0,0,0
2995,2996,0,en,9.853270,0.216667,4/22/94,102.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It was supposed to be a routine prisoner trans...,...,0,0,0,0,0,0,0,0,0,0
2996,2997,0,sv,3.727996,-0.200000,3/28/13,102.0,"[{'iso_639_1': 'sv', 'name': 'svenska'}]",Released,NaN,...,0,0,0,0,0,0,0,0,0,0
2997,2998,65000000,en,14.482345,0.263889,10/11/96,120.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,What's forgotten is not always gone.,...,0,0,0,0,0,0,0,0,0,0
2998,2999,42000000,en,15.725542,0.148889,1/16/04,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"For the most cautious man on Earth, life is ab...",...,0,0,0,0,0,0,0,0,0,0
2999,3000,35000000,en,10.512109,-0.050000,9/22/11,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,They stole his life. He's taking it back.,...,0,0,0,0,0,0,0,0,0,0

In [489]:
train.drop(['spoken_languages'],inplace=True,axis=1)

In [490]:
train.to_csv('train_c2',index=False)

In [492]:
train['tagline'].fillna('unknown',inplace=True)

In [493]:
tl=[]
for i in range(0,train.shape[0]):
    blob=TextBlob(train['tagline'][i])
    tl.append(blob.sentiment.polarity)

In [495]:
train.insert(5,'movie_sentiment2',tl)

In [497]:
train.drop(['tagline'],inplace=True,axis=1)

In [516]:
kw=train['Keywords'].str.split(',',n=100,expand=True)

In [520]:
kw=kw.iloc[:,np.arange(1,71,2)]

In [522]:
kw.loc[:,69].notnull().sum()

8

In [523]:
kw.fillna('unknown',inplace=True)

In [524]:
for j in range(0,kw.shape[1]):
    kw1=kw.iloc[:,j]
    import re
    for i in range(0,kw1.shape[0]):
        m=re.search(': (.+?)}',kw1[i])
        if m:
            found=m.group(1)
            kw1[i]=found[1:-1]

In [526]:
unique_kw=kw.loc[:,1].value_counts()

In [531]:
unique_kw=unique_kw.index[0:20]

In [532]:
unique_kw

Index(['unknown', 'based on novel', 'independent film', 'prison', 'new york',
       'paris', 'sex', 'london england', 'female nudity', 'suicide',
       'father son relationship', 'gay', 'love triangle', 'corruption',
       'brother brother relationship', 'woman director', 'sport',
       'male nudity', 'biography', 'holiday'],
      dtype='object')

In [534]:
new_kw=pd.DataFrame(columns=unique_kw,index=np.arange(0,3000,1))

In [535]:
for j in range(0,len(new_kw.columns)):
    for i in range(0,kw.shape[0]):
        med=new_kw.iloc[:,j]
        med[i]=(new_kw.columns[j]==kw.iloc[i,:]).sum()

In [537]:
new_kw.drop(['unknown'],inplace=True,axis=1)

In [539]:
kw

,1,3,5,7,9,11,13,15,17,19,...,51,53,55,57,59,61,63,65,67,69
0,time travel,sequel,hot tub,duringcreditsstinger,unknown,unknown,unknown,unknown,unknown,unknown,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
1,coronation,duty,marriage,falling in love,unknown,unknown,unknown,unknown,unknown,unknown,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2,jazz,obsession,conservatory,music teacher,new york city,violence,montage,drummer,public humiliation,jazz band,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
3,mystery,bollywood,police corruption,crime,india,missing husband,nerve gas,unknown,unknown,unknown,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
4,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
5,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
6,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
7,journalism,translation,television,manipulation of the media,iraq,reporter,woman director,unknown,unknown,unknown,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
8,island,pirate gang,puppet,treasure hunt,unknown,unknown,unknown,unknown,unknown,unknown,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
9,mockumentary,folk singer,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
10,underdog,philadelphia,transporter,italo-american,fight,love of one's life,publicity,boxer,independence,boxing match,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
11,nerd,vacation,farce,jock,frame up,defector,unknown,unknown,unknown,unknown,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
12,male nudity,female nudity,adultery,parent child relationship,midlife crisis,coming out,first time,camcorder,virgin,nudity,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
13,baseball bat,widow,recording contract,recording studio,russian mafia,music business,night club,pawnshop,unknown,unknown,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
14,self-fulfilling prophecy,washington d.c.,evidence,future,hologram,dystopia,murder,neo-noir,future noir,unknown,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
15,skinhead,serbia,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
16,hostage,menace,hitman,airplane,unknown,unknown,unknown,unknown,unknown,unknown,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
17,biography,charles dickens,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
18,competition,snowboarding,birthday party,chalet,snowboarding competition,skiing,engagement party,unknown,unknown,unknown,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
19,martial arts,war on drugs,kidnapping,bodyguard,baby-snatching,unknown,unknown,unknown,unknown,unknown,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
20,time travel,sabotage,deep space explorer,unknown,unknown,unknown,unknown,unknown,unknown,unknown,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
21,lake,summer camp,murder,serial killer,slasher,summer,jason voorhees,one by one,friday the thirteenth,unknown,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
22,webcam,anthology,vhs,burglary,split screen,found footage,mumblecore,ghost child,boxer shorts,vcr,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
23,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
24,new zealand,sheep,animal horror,unknown,unknown,unknown,unknown,unknown,unknown,unknown,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
25,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
26,dialogue,confidence,invention,independent film,unknown,unknown,unknown,unknown,unknown,unknown,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
27,male female relationship,best friend,falling in love,unknown,unknown,unknown,unknown,unknown,unknown,unknown,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
28,toy,transformation,based on toy,transformers,robots,intergalactic war,unknown,unknown,unknown,unknown,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
29,new york,custody battle,suspense,lawyer,unknown,unknown,unknown,unknown,unknown,unknown,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2970,sister sister relationship,anonymous letter,diva,bodyguard,oscar award,los angeles,unknown,unknown,unknown,unknown,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2971,wish,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2972,kung fu,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2973,time travel,dinosaur,science,unknown,unknown,unknown,unknown,unknown,unknown,unknown,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2974,detective,monster,professor,island,museum,darkness,alien life-form,paranormal,artifact,slow motion scene,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2975,alien,comedy,duringcreditsstinger,beforecreditsstinger,live action and animation,unknown,unknown,unknown,unknown,unknown,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2976,suspicion,suspect,investigation,remake,murder,death,accident,dysfunctional,unknown,unknown,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2977,car crash,police officer,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2978,gay,great britain,narration,glam rock,bisexual,music journalism,school uniform,\xa0begins with text,imaginary band,baby left on doorstep,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2979,kiss,sperm bank,romantic comedy,male female relationship,doctor,pregnancy,single mother,artificial insemination,motherhood,duringcreditsstinger,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2980,suicide attempt,robber,police,illegal drugs,dog attack,malayalam,real life,unknown,unknown,unknown,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2981,misfits,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2982,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2983,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2984,liberation,transport of prisoners,special unit,weapon,los angeles,unknown,unknown,unknown,unknown,unknown,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2985,black people,new jersey,lie,psychological stress,baby-snatching,psychopathy,xenophobia,psychiatric,unknown,unknown,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2986,independent film,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2987,monster,mutant,biological weapon,post-apocalyptic,laboratory,vaccine,desert,walkie talkie,flame thrower,rattlesnake,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2988,sister sister relationship,prayer,divorcee,illegal prostitution,unknown,unknown,unknown,unknown,unknown,unknown,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2989,trumpet,swan,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2990,burglar,restaurant,millionaire,guilt,irreverence,nephew,unknown,unknown,unknown,unknown,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2991,ballet dancer,musical,ballet,unknown,unknown,unknown,unknown,unknown,unknown,unknown,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2992,male nudity,treasure,magic,palace,flying carpet,bagdad,rope,princess,thief,suitor,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2993,new york,airport,marriage proposal,translation,craftsman,stewardess,illegal immigration,language barrier,jfk international airport,immigration law,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2994,sport,anti semitism,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2995,prison,sex,handcuffs,waitress,fight,fireworks,nudity,volcano,navy,road trip,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2996,sweden,punk,based on comic,all girl band,girl band,foreign,unknown,unknown,unknown,unknown,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2997,assassination,amnesia,hostage,chase,dark comedy,teacher,escape,single mother,timebomb,candlelight vigil,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2998,beach,honeymoon,bride,chance,risk,relation,long island,romantic comedy,comedy,scuba diving,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2999,cia,airport,hero,fight,kidnapping,time bomb,training,webcam,website,party,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown

In [541]:
new_kw.iloc[:,0].value_counts()

0    2889
1     111
Name: based on novel, dtype: int64

In [542]:
new_kw.to_csv('new_kw',index=False)

In [544]:
train.drop(['Keywords'],inplace=True,axis=1)

In [545]:
train.to_csv('train_c3',index=False)

In [551]:
train.drop(['cast','crew'],inplace=True,axis=1)

In [552]:
train.to_csv('train_c3',index=False)

In [554]:
nul=train.isnull().sum()

In [557]:
def KNN(data,count=3):
    from sklearn.metrics.pairwise import euclidean_distances
    m=data.isnull().sum()
    mis=[]
    data1=data.copy()
    for i in range(0,data.shape[1]):
        if(m[i]>0):
            mis.append(data.columns[i]) 
        if(len(data.iloc[:,i].value_counts())>50 and data.dtypes[i]=="O"):
            data1.drop(data.columns[i],axis=1,inplace=True)
        if(len(data.iloc[:,i].value_counts())<2):
            data1.drop(data.columns[i],axis=1,inplace=True)
    data1.drop(mis,axis=1,inplace=True)  
    print('Number of columns removed for processing is',len(data.columns)-len(data1.columns))
    for i in range(0,data1.shape[1]):
        if(data1.dtypes[i]=='O'):
            data1.iloc[:,i]=data1.iloc[:,i].astype('category')
    data1=pd.get_dummies(data1,drop_first=True) 
    for i in range(data1.shape[1]):
        data1.iloc[:,i]=(data1.iloc[:,i]-min(data1.iloc[:,i]))/(max(data1.iloc[:,i])-min(data1.iloc[:,i]))  
    for i in mis:
        mi=data[data.loc[:,i].isnull()==True].index
        nu=data[data.loc[:,i].isnull()==False].index
        ary = euclidean_distances(data1.loc[mi,:], data1.loc[nu,:])
        ary=pd.DataFrame(ary)
        ary.index=mi
        ary.columns=nu
        n=0
        if(data.dtypes[data.columns.get_loc(i)]=='O'):
            for j in mi:
                cot=ary.loc[j,:].nsmallest(count)
                cot=cot.index
                val=data.loc[cot,i]
                val=val.mode()
                val=pd.DataFrame(val)
                val=val.iloc[0,0]
                data.loc[j,i]=val
        else:
            for j in mi:
                cot=ary.loc[j,:].nsmallest(count)
                cot=cot.index
                val=data.loc[cot,i]   
                val=val.mean()
                data.loc[j,i]=val
    return(data)

In [558]:
train=KNN(train)

Number of columns removed for processing is 2

In [566]:
train.dtypes

id                     int64
budget                 int64
original_language     object
popularity           float64
movie_sentiment      float64
movie_sentiment2     float64
release_date          object
runtime              float64
status                object
revenue                int64
War                    int64
Music                  int64
Comedy                 int64
Action                 int64
Adventure              int64
TV Movie               int64
Drama                  int64
History                int64
Family                 int64
Western                int64
Foreign                int64
Thriller               int64
Mystery                int64
Crime                  int64
Animation              int64
Horror                 int64
Science Fiction        int64
Documentary            int64
Romance                int64
Fantasy                int64
                      ...
Belgium                int64
New Zealand            int64
Brazil                 int64
English                int64
Français               int64
Español                int64
Pусский                int64
Deutsch                int64
日本語                    int64
हिन्दी                 int64
广州话 / 廣州話              int64
Italiano               int64
普通话                    int64
العربية                int64
Český                  int64
தமிழ்                  int64
한국어/조선말                int64
                       int64
svenska                int64
Português              int64
Nederlands             int64
Dansk                  int64
No Language            int64
Latin                  int64
فارسی                  int64
suomi                  int64
Polski                 int64
עִבְרִית               int64
ελληνικά               int64
Afrikaans              int64
Length: 76, dtype: object

In [567]:
train['release_date']=pd.to_datetime(train['release_date'])

In [575]:
min_time=min(train['release_date'])

In [579]:
train['release_date']=(train['release_date']-min_time)/dt.timedelta(days=1)

In [568]:
def to_dummy(data):
    ty=data.dtypes
    cat=[]
    for i in range(0,len(data.columns)):
        if(ty[i]=='object'):
            data.iloc[:,i]=data.iloc[:,i].astype('category')
    data=pd.get_dummies(data,drop_first=True)
    return(data)

In [569]:
train=to_dummy(train)

In [593]:
train.shape

(3000, 109)

In [610]:
train_m=train.iloc[:,0:7]

In [655]:
y=train.loc[:,'revenue']
x=train.drop(['revenue'],axis=1)

In [656]:
y=y/100000

In [632]:
#creating loop to return RMSE and MAPE for train and test data with cross validation

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
test_rmse=[]
test_mape=[]
train_rmse=[]
train_mape=[]

for i in range(0,1):
    #sampling
    x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)
    #building model                                                       #adjusting parameters to reduce overfitting
    regressor=RandomForestRegressor(max_depth=30,min_samples_split=2,min_samples_leaf=1,max_features='auto',min_impurity_decrease=0,max_leaf_nodes=40)
    regressor.fit(x_train,y_train)
    #predicting results for test
    y_pred=regressor.predict(x_test)
    #converting to array
    y_pred=np.array(y_pred)
    y_test=np.array(y_test)
    #calculating error RMSE
    error=y_pred-y_test
    error2=error**2
    test_rmse.append(np.sqrt(error2.sum()/len(error2)))
    #MAPE error
    error=abs(error)
    error_per=(error/y_test)*100
    test_mape.append(np.mean(error_per))
        #predicting results for train
    y_pred=regressor.predict(x_train)
    #converting to array
    y_pred=np.array(y_pred)
    y_train=np.array(y_train)
    #calculating error RMSE
    error=y_pred-y_train
    error2=error**2
    train_rmse.append(np.sqrt(error2.sum()/len(error2)))
    #MAPE error
    error=abs(error)
    error_per=(error/y_train)*100
    train_mape.append(np.mean(error_per))
    
c=[np.mean(test_rmse),np.mean(test_mape)]
c1=[np.mean(train_rmse),np.mean(train_mape)]

c=pd.DataFrame(c)
c1=pd.DataFrame(c1)
result=pd.concat([c,c1],axis=1)
result.columns=['test','train']
result.index=['RMSE error','MAPE(%) error']
result

C:\Users\LENOVO\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

                       test         train
RMSE error     9.182178e+02  5.616980e+02
MAPE(%) error  1.707168e+06  3.696581e+06

In [665]:
#creating loop to return RMSE and MAPE for train and test data with cross validation

from sklearn.model_selection import train_test_split
import xgboost as xgb
test_rmse=[]
test_mape=[]
train_rmse=[]
train_mape=[]

#building model
regressor=xgb.XGBRegressor()#max_depth=6,n_estimators=100,colsample_bytree=0.6,learning_rate=0.05,subsample=0.8,colsample_bylevel=1,gamma=0)

for i in range(0,1):
    #sampling
    x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)
    #fitting data
    regressor.fit(x_train,y_train)
    #predicting results for test
    y_pred=regressor.predict(x_test)
    #converting to array
    y_pred=np.array(y_pred)
    y_test=np.array(y_test)
    #calculating error RMSE
    error=y_pred-y_test
    error2=error**2
    test_rmse.append(np.sqrt(error2.sum()/len(error2)))
    #MAPE error
    error=abs(error)
    error_per=(error/y_test)*100
    test_mape.append(np.mean(error_per))
    #predicting results for train
    y_pred=regressor.predict(x_train)
    #converting to array
    y_pred=np.array(y_pred)
    y_train=np.array(y_train)
    #calculating error RMSE
    error=y_pred-y_train
    error2=error**2
    train_rmse.append(np.sqrt(error2.sum()/len(error2)))
    #MAPE error
    error=abs(error)
    error_per=(error/y_train)*100
    train_mape.append(np.mean(error_per))
    
c=[np.mean(test_rmse),np.mean(test_mape)]
c1=[np.mean(train_rmse),np.mean(train_mape)]

c=pd.DataFrame(c)
c1=pd.DataFrame(c1)
result=pd.concat([c,c1],axis=1)
result.columns=['test','train']
result.index=['RMSE error','MAPE(%) error']
result

                        test         train
RMSE error        824.287116  5.602278e+02
MAPE(%) error  506997.940089  2.803806e+06

In [607]:
train.to_csv('train_f',index=False)